In [1]:
from pathlib import Path
import pandas as pd

# Path to PriceSense raw data
RAW_DIR = Path.home() / "Desktop" / "PriceSense" / "data" / "raw"

print("Raw data folder:")
print(RAW_DIR)
print()

# Check whether the folder exists
print("Folder exists:", RAW_DIR.exists())
print()

# List files
files = sorted(RAW_DIR.iterdir())

print("Files found:")
for file in files:
    print(f"{file.name:30} | {file.stat().st_size / (1024**2):,.2f} MB")

print("\n" + "=" * 70)

# Read only the first line of each file to inspect column headers
print("COLUMN HEADERS")
print("=" * 70)

for file in files:
    if file.is_file():
        with open(file, "r", encoding="utf-8-sig") as f:
            header = f.readline().strip()

        print(f"\n{file.name}")
        print(header)

Raw data folder:
C:\Users\ADMIN\Desktop\PriceSense\data\raw

Folder exists: True

Files found:
actual_matrix.csv              | 1.06 MB
catalog.csv                    | 24.08 MB
discounts_history.csv          | 325.66 MB
markdowns.csv                  | 0.41 MB
online.csv                     | 54.21 MB
price_history.csv              | 27.92 MB
sales.csv                      | 361.67 MB
stores.csv                     | 0.00 MB

======================================================================
COLUMN HEADERS
======================================================================

actual_matrix.csv
,item_id,date,store_id

catalog.csv
,item_id,dept_name,class_name,subclass_name,item_type,weight_volume,weight_netto,fatness

discounts_history.csv
,date,item_id,sale_price_before_promo,sale_price_time_promo,promo_type_code,doc_id,number_disc_day,store_id

markdowns.csv
,date,item_id,normal_price,price,quantity,store_id

online.csv
,date,item_id,quantity,price_base,sum_total,store_id

price_history.csv
,date,item_id,price,code,store_id

sales.csv
,date,item_id,quantity,price_base,sum_total,store_id

stores.csv
,store_id,division,format,city,area

In [2]:
import csv

print("RAW DATASET ROW COUNTS")
print("=" * 70)

for file in sorted(RAW_DIR.glob("*.csv")):
    with open(file, "rb") as f:
        row_count = sum(1 for _ in f) - 1  # subtract header

    print(f"{file.name:30} {row_count:>12,} rows")

print("\n" + "=" * 70)
print("SAMPLE RECORDS")
print("=" * 70)

# Read only 3 rows from each file
for file in sorted(RAW_DIR.glob("*.csv")):
    sample = pd.read_csv(file, nrows=3)

    print(f"\n{file.name}")
    print("Shape:", sample.shape)
    display(sample)

RAW DATASET ROW COUNTS
======================================================================
actual_matrix.csv                    35,202 rows
catalog.csv                         219,810 rows
discounts_history.csv             3,746,744 rows
markdowns.csv                         8,979 rows
online.csv                        1,123,412 rows
price_history.csv                   698,626 rows
sales.csv                         7,432,685 rows
stores.csv                                4 rows

======================================================================
SAMPLE RECORDS
======================================================================

actual_matrix.csv
Shape: (3, 4)

   Unnamed: 0       item_id        date  store_id
0           0  c578da8e8841  2019-10-17         1
1           1  4dd2b686802c  2019-10-17         1
2           2  16ade2e3fca9  2019-10-17         1

catalog.csv
Shape: (3, 9)

,Unnamed: 0,item_id,dept_name,class_name,subclass_name,item_type,weight_volume,weight_netto,fatness
0,0,da17e2d5feda,БУМАЖНО-ВАТНАЯ ПРОДУКЦИЯ,БУМАЖНАЯ ПРОДУКЦИЯ,ВЛАЖНЫЕ САЛФЕТКИ,NaN,150.0,NaN,NaN
1,1,614de2b96018,БУМАЖНО-ВАТНАЯ ПРОДУКЦИЯ,ВАТНАЯ ПРОДУКЦИЯ,ВАТНЫЕ ДИСКИ,NaN,30.0,NaN,NaN
2,2,0c1f1f3e3e11,БУМАЖНО-ВАТНАЯ ПРОДУКЦИЯ,ВАТНАЯ ПРОДУКЦИЯ,ВАТНЫЕ ДИСКИ,NaN,NaN,NaN,NaN

discounts_history.csv
Shape: (3, 9)

,Unnamed: 0,date,item_id,sale_price_before_promo,sale_price_time_promo,promo_type_code,doc_id,number_disc_day,store_id
0,3648316,2022-08-28,cde97a9ec3ef,729.9,669.9,6.0,89ea9f0c-1c08-11ed-ad4d-005056861040,13.0,1
1,3648317,2022-08-28,2906fbc9e11c,129.9,99.9,NaN,039e85df-1e51-11ed-ad4d-005056861040,11.0,1
2,3648318,2022-08-28,c48c3a3d8c01,129.9,99.9,NaN,039e85df-1e51-11ed-ad4d-005056861040,11.0,1

markdowns.csv
Shape: (3, 7)

,Unnamed: 0,date,item_id,normal_price,price,quantity,store_id
0,0,2023-08-01,bc2f82a22e11,189.0,100.0,8.0,1
1,1,2023-08-01,389412076801,179.0,100.0,5.0,1
2,2,2023-08-01,0e39cf5d57c1,149.0,100.0,5.0,1

online.csv
Shape: (3, 7)

,Unnamed: 0,date,item_id,quantity,price_base,sum_total,store_id
0,0,2023-08-04,4aa8dbe05246,3.0,12.40,37.21,1
1,1,2023-08-04,4e0fbcf99cf9,2.0,56.27,112.54,1
2,2,2023-08-04,2e008b673129,2.0,56.27,112.54,1

price_history.csv
Shape: (3, 6)

   Unnamed: 0        date       item_id  price        code  store_id
0           0  2023-08-01  4a1f95fe4d4b  499.9           1         1
1           1  2023-08-01  bf43a9d3ae13    0.0  9999999999         1
2           2  2023-08-01  0dd8744decce  129.9           1         1

sales.csv
Shape: (3, 7)

,Unnamed: 0,date,item_id,quantity,price_base,sum_total,store_id
0,0,2023-08-04,293375605257,1.000,47.86,47.86,1
1,1,2023-08-04,a66fdf2c0ae7,3.000,49.60,148.80,1
2,2,2023-08-04,daa46ef49b7a,0.822,379.00,311.54,1

stores.csv
Shape: (3, 6)

   Unnamed: 0  store_id division            format   city  area
0           0         4     Div1          MaxiEuro  City3  1887
1           1         3     Div2  Format-7 express  City2   109
2           2         2     Div2          Format-6  City1   210

In [3]:
from collections import defaultdict
import numpy as np

# ---------------------------------------------------------
# Day 1 — Structural profiling
# ---------------------------------------------------------

profile = {}

for file in sorted(RAW_DIR.glob("*.csv")):

    print(f"\nProfiling: {file.name}")

    # Read in chunks so large files do not overwhelm RAM
    chunksize = 500_000

    row_count = 0
    null_counts = defaultdict(int)

    min_date = None
    max_date = None

    unique_items = set()
    unique_stores = set()

    for chunk in pd.read_csv(
        file,
        chunksize=chunksize,
        low_memory=False
    ):

        row_count += len(chunk)

        # Remove exported index column from profiling
        if "Unnamed: 0" in chunk.columns:
            chunk = chunk.drop(columns="Unnamed: 0")

        # Null counts
        for col in chunk.columns:
            null_counts[col] += int(chunk[col].isna().sum())

        # Date range
        if "date" in chunk.columns:
            dates = pd.to_datetime(chunk["date"], errors="coerce")

            chunk_min = dates.min()
            chunk_max = dates.max()

            if pd.notna(chunk_min):
                min_date = chunk_min if min_date is None else min(min_date, chunk_min)

            if pd.notna(chunk_max):
                max_date = chunk_max if max_date is None else max(max_date, chunk_max)

        # Unique items
        if "item_id" in chunk.columns:
            unique_items.update(chunk["item_id"].dropna().unique())

        # Unique stores
        if "store_id" in chunk.columns:
            unique_stores.update(chunk["store_id"].dropna().unique())

    profile[file.name] = {
        "rows": row_count,
        "columns": list(null_counts.keys()),
        "null_counts": dict(null_counts),
        "date_min": min_date,
        "date_max": max_date,
        "unique_items": len(unique_items),
        "unique_stores": len(unique_stores)
    }

# ---------------------------------------------------------
# Display summary
# ---------------------------------------------------------

summary = []

for filename, info in profile.items():
    summary.append({
        "file": filename,
        "rows": info["rows"],
        "columns": len(info["columns"]),
        "date_min": info["date_min"],
        "date_max": info["date_max"],
        "unique_items": info["unique_items"],
        "unique_stores": info["unique_stores"]
    })

summary_df = pd.DataFrame(summary)

display(summary_df)

print("\n" + "=" * 70)
print("NULL VALUES")
print("=" * 70)

for filename, info in profile.items():
    print(f"\n{filename}")

    null_df = pd.DataFrame(
        list(info["null_counts"].items()),
        columns=["column", "null_count"]
    )

    null_df = null_df[null_df["null_count"] > 0]

    if null_df.empty:
        print("No null values.")
    else:
        display(null_df)

Profiling: actual_matrix.csv

Profiling: catalog.csv

Profiling: discounts_history.csv

Profiling: markdowns.csv

Profiling: online.csv

Profiling: price_history.csv

Profiling: sales.csv

Profiling: stores.csv

,file,rows,columns,date_min,date_max,unique_items,unique_stores
0,actual_matrix.csv,35202,3,2019-10-17,2024-09-26,15398,4
1,catalog.csv,219810,8,NaT,NaT,219810,0
2,discounts_history.csv,3746744,8,2022-08-28,2045-12-31,16081,4
3,markdowns.csv,8979,6,2022-08-28,2024-09-26,313,3
4,online.csv,1123412,6,2022-08-28,2024-09-26,18405,2
5,price_history.csv,698626,5,2022-08-28,2024-09-26,37624,4
6,sales.csv,7432685,6,2022-08-28,2024-09-26,28182,4
7,stores.csv,4,5,NaT,NaT,0,4

======================================================================
NULL VALUES
======================================================================

actual_matrix.csv
No null values.

catalog.csv

          column  null_count
4      item_type      176224
5  weight_volume      136858
6   weight_netto      170853
7        fatness      212598

discounts_history.csv

            column  null_count
4  promo_type_code      317846

markdowns.csv
No null values.

online.csv
No null values.

price_history.csv
No null values.

sales.csv
No null values.

stores.csv
No null values.

In [1]:
import pandas as pd

sales_sample = pd.read_csv(
    r"C:\Users\ADMIN\Desktop\PriceSense\data\raw\sales.csv",
    nrows=5
)

sales_sample.info()
sales_sample

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5 non-null      int64
 1   date        5 non-null      str
 2   item_id     5 non-null      str
 3   quantity    5 non-null      float64
 4   price_base  5 non-null      float64
 5   sum_total   5 non-null      float64
 6   store_id    5 non-null      int64
dtypes: float64(3), int64(2), str(2)
memory usage: 522.0 bytes

,Unnamed: 0,date,item_id,quantity,price_base,sum_total,store_id
0,0,2023-08-04,293375605257,1.000,47.86,47.86,1
1,1,2023-08-04,a66fdf2c0ae7,3.000,49.60,148.80,1
2,2,2023-08-04,daa46ef49b7a,0.822,379.00,311.54,1
3,3,2023-08-04,a3b49c1bf758,1.000,129.00,129.00,1
4,4,2023-08-04,ab611c5cef62,7.000,79.90,559.30,1

In [3]:
catalog_sample = pd.read_csv(
    r"C:\Users\ADMIN\Desktop\PriceSense\data\raw\catalog.csv",
    nrows=5
)

catalog_sample.info()
catalog_sample

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     5 non-null      int64
 1   item_id        5 non-null      str
 2   dept_name      5 non-null      str
 3   class_name     5 non-null      str
 4   subclass_name  5 non-null      str
 5   item_type      0 non-null      float64
 6   weight_volume  3 non-null      float64
 7   weight_netto   0 non-null      float64
 8   fatness        0 non-null      float64
dtypes: float64(4), int64(1), str(4)
memory usage: 1.0 KB

,Unnamed: 0,item_id,dept_name,class_name,subclass_name,item_type,weight_volume,weight_netto,fatness
0,0,da17e2d5feda,БУМАЖНО-ВАТНАЯ ПРОДУКЦИЯ,БУМАЖНАЯ ПРОДУКЦИЯ,ВЛАЖНЫЕ САЛФЕТКИ,NaN,150.0,NaN,NaN
1,1,614de2b96018,БУМАЖНО-ВАТНАЯ ПРОДУКЦИЯ,ВАТНАЯ ПРОДУКЦИЯ,ВАТНЫЕ ДИСКИ,NaN,30.0,NaN,NaN
2,2,0c1f1f3e3e11,БУМАЖНО-ВАТНАЯ ПРОДУКЦИЯ,ВАТНАЯ ПРОДУКЦИЯ,ВАТНЫЕ ДИСКИ,NaN,NaN,NaN,NaN
3,3,71a7fa99f005,ТОВАРЫ ДЛЯ ДОМА,ПОСУДА,КУХОННАЯ ПОСУДА,NaN,NaN,NaN,NaN
4,4,ec1bd4d59fe9,БУМАЖНО-ВАТНАЯ ПРОДУКЦИЯ,ВАТНАЯ ПРОДУКЦИЯ,ВАТНЫЕ ДИСКИ,NaN,30.0,NaN,NaN

In [4]:
discounts_sample = pd.read_csv(
    r"C:\Users\ADMIN\Desktop\PriceSense\data\raw\discounts_history.csv",
    nrows=5
)

discounts_sample.info()
discounts_sample

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               5 non-null      int64
 1   date                     5 non-null      str
 2   item_id                  5 non-null      str
 3   sale_price_before_promo  5 non-null      float64
 4   sale_price_time_promo    5 non-null      float64
 5   promo_type_code          1 non-null      float64
 6   doc_id                   5 non-null      str
 7   number_disc_day          5 non-null      float64
 8   store_id                 5 non-null      int64
dtypes: float64(4), int64(2), str(3)
memory usage: 782.0 bytes

,Unnamed: 0,date,item_id,sale_price_before_promo,sale_price_time_promo,promo_type_code,doc_id,number_disc_day,store_id
0,3648316,2022-08-28,cde97a9ec3ef,729.9,669.9,6.0,89ea9f0c-1c08-11ed-ad4d-005056861040,13.0,1
1,3648317,2022-08-28,2906fbc9e11c,129.9,99.9,NaN,039e85df-1e51-11ed-ad4d-005056861040,11.0,1
2,3648318,2022-08-28,c48c3a3d8c01,129.9,99.9,NaN,039e85df-1e51-11ed-ad4d-005056861040,11.0,1
3,3648319,2022-08-28,f85243ca61e6,129.9,99.9,NaN,039e85df-1e51-11ed-ad4d-005056861040,11.0,1
4,3648320,2022-08-28,27ce75534065,129.9,99.9,NaN,039e85df-1e51-11ed-ad4d-005056861040,11.0,1

In [5]:
price_sample = pd.read_csv(
    r"C:\Users\ADMIN\Desktop\PriceSense\data\raw\price_history.csv",
    nrows=5
)

price_sample.info()
price_sample

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5 non-null      int64
 1   date        5 non-null      str
 2   item_id     5 non-null      str
 3   price       5 non-null      float64
 4   code        5 non-null      int64
 5   store_id    5 non-null      int64
dtypes: float64(1), int64(3), str(2)
memory usage: 482.0 bytes

   Unnamed: 0        date       item_id  price        code  store_id
0           0  2023-08-01  4a1f95fe4d4b  499.9           1         1
1           1  2023-08-01  bf43a9d3ae13    0.0  9999999999         1
2           2  2023-08-01  0dd8744decce  129.9           1         1
3           3  2023-08-01  9b38c7e4dba9  136.0           1         1
4           4  2023-08-01  b791e8c9347c    0.0           1         1

In [6]:
markdowns_sample = pd.read_csv(
    r"C:\Users\ADMIN\Desktop\PriceSense\data\raw\markdowns.csv",
    nrows=5
)

markdowns_sample.info()
markdowns_sample

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    5 non-null      int64
 1   date          5 non-null      str
 2   item_id       5 non-null      str
 3   normal_price  5 non-null      float64
 4   price         5 non-null      float64
 5   quantity      5 non-null      float64
 6   store_id      5 non-null      int64
dtypes: float64(3), int64(2), str(2)
memory usage: 522.0 bytes

,Unnamed: 0,date,item_id,normal_price,price,quantity,store_id
0,0,2023-08-01,bc2f82a22e11,189.0,100.0,8.0,1
1,1,2023-08-01,389412076801,179.0,100.0,5.0,1
2,2,2023-08-01,0e39cf5d57c1,149.0,100.0,5.0,1
3,3,2023-08-01,dd94e2bc5601,149.0,100.0,1.0,1
4,4,2023-08-01,e60d890f2812,369.0,270.0,1.0,1

In [7]:
online_sample = pd.read_csv(
    r"C:\Users\ADMIN\Desktop\PriceSense\data\raw\online.csv",
    nrows=5
)

online_sample.info()
online_sample

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5 non-null      int64
 1   date        5 non-null      str
 2   item_id     5 non-null      str
 3   quantity    5 non-null      float64
 4   price_base  5 non-null      float64
 5   sum_total   5 non-null      float64
 6   store_id    5 non-null      int64
dtypes: float64(3), int64(2), str(2)
memory usage: 522.0 bytes

,Unnamed: 0,date,item_id,quantity,price_base,sum_total,store_id
0,0,2023-08-04,4aa8dbe05246,3.0,12.40,37.21,1
1,1,2023-08-04,4e0fbcf99cf9,2.0,56.27,112.54,1
2,2,2023-08-04,2e008b673129,2.0,56.27,112.54,1
3,3,2023-08-04,49db9c973903,1.0,29.94,29.94,1
4,4,2023-08-04,9d6072422e8e,1.0,80.10,80.10,1

In [8]:
actual_sample = pd.read_csv(
    r"C:\Users\ADMIN\Desktop\PriceSense\data\raw\actual_matrix.csv",
    nrows=5
)

actual_sample.info()
actual_sample

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5 non-null      int64
 1   item_id     5 non-null      str
 2   date        5 non-null      str
 3   store_id    5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 402.0 bytes

   Unnamed: 0       item_id        date  store_id
0           0  c578da8e8841  2019-10-17         1
1           1  4dd2b686802c  2019-10-17         1
2           2  16ade2e3fca9  2019-10-17         1
3           3  f4eb16dab09e  2019-10-17         1
4           4  ab1384c2af6d  2020-05-31         1

In [9]:
stores_sample = pd.read_csv(
    r"C:\Users\ADMIN\Desktop\PriceSense\data\raw\stores.csv",
    nrows=5
)

stores_sample.info()
stores_sample

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  4 non-null      int64
 1   store_id    4 non-null      int64
 2   division    4 non-null      str
 3   format      4 non-null      str
 4   city        4 non-null      str
 5   area        4 non-null      int64
dtypes: int64(3), str(3)
memory usage: 400.0 bytes

   Unnamed: 0  store_id division            format   city  area
0           0         4     Div1          MaxiEuro  City3  1887
1           1         3     Div2  Format-7 express  City2   109
2           2         2     Div2          Format-6  City1   210
3           3         1     Div1          Format-1  City1  1500