In [1]:
import pandas as pd
import numpy as np

from sqlalchemy import create_engine

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
%pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in C:\Users\ADMIN\anaconda3\Lib\site-packages (2.9.13)
Note: you may need to restart the kernel to use updated packages.

In [3]:
DB_USER = "postgres"
DB_PASSWORD = "2004"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "pricesense"

engine = create_engine(
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

print("PostgreSQL connection created.")

PostgreSQL connection created.

In [4]:
query = """
SELECT
    COUNT(*) AS row_count,
    COUNT(DISTINCT source_row_id) AS unique_rows,
    MIN(date) AS min_date,
    MAX(date) AS max_date
FROM analytics.price_sense_features;
"""

check = pd.read_sql(query, engine)

check

   row_count  unique_rows    min_date    max_date
0    7432685      7432685  2022-08-28  2024-09-26

In [5]:
pd.read_sql(
    """
    SELECT COUNT(*) AS row_count
    FROM analytics.price_sense_features;
    """,
    engine
)

   row_count
0    7432685

In [6]:
result = pd.read_sql(
    "SELECT COUNT(*) AS row_count FROM analytics.price_sense_features;",
    engine
)

print("Rows:", result.iloc[0]["row_count"])

Rows: 7432685

In [7]:
columns = pd.read_sql(
    """
    SELECT column_name, data_type
    FROM information_schema.columns
    WHERE table_schema = 'analytics'
      AND table_name = 'price_sense_features'
    ORDER BY ordinal_position;
    """,
    engine
)

print(columns.to_string(index=False))

                   column_name        data_type
                 source_row_id           bigint
                          date             date
                       item_id             text
                      store_id          integer
                      quantity double precision
                         price double precision
                     sum_total double precision
                          year          integer
                         month          integer
                          week          integer
                   day_of_week          integer
                    is_weekend          integer
                     dept_name             text
                    class_name             text
                 subclass_name             text
                     item_type             text
                 weight_volume double precision
                  weight_netto double precision
                       fatness double precision
                      division             text
                        format             text
                          city             text
                          area          integer
          store_demand_avg_28d double precision
                previous_price double precision
                promotion_flag          integer
               promo_type_code double precision
                    time_promo double precision
                  discount_pct double precision
                quantity_lag_1 double precision
                quantity_lag_7 double precision
               quantity_lag_14 double precision
               quantity_lag_28 double precision
                 demand_avg_7d double precision
                demand_avg_28d double precision
         demand_volatility_28d double precision
               demand_trend_7d double precision
         price_vs_previous_pct double precision
            demand_momentum_7d double precision
            demand_vs_baseline double precision
    promo_discount_interaction double precision
promo_price_change_interaction double precision
                 markdown_flag          integer
                  markdown_pct double precision

In [8]:
sample = pd.read_sql(
    """
    SELECT *
    FROM analytics.price_sense_features
    ORDER BY date, item_id, store_id
    LIMIT 5;
    """,
    engine
)

sample

,source_row_id,date,item_id,store_id,quantity,price,sum_total,year,month,week,...,demand_avg_28d,demand_volatility_28d,demand_trend_7d,price_vs_previous_pct,demand_momentum_7d,demand_vs_baseline,promo_discount_interaction,promo_price_change_interaction,markdown_flag,markdown_pct
0,11783134,2022-08-28,001829cb707d,1,7.0,134.76,943.32,2022,8,34,...,None,None,None,None,None,None,0.0,0.0,0,None
1,15978661,2022-08-28,001829cb707d,2,1.0,148.00,148.00,2022,8,34,...,None,None,None,None,None,None,0.0,0.0,0,None
2,11785258,2022-08-28,0022b986c8f0,1,2.0,59.90,119.80,2022,8,34,...,None,None,None,None,None,None,0.0,0.0,0,None
3,15978392,2022-08-28,00274a69c705,2,1.0,35.90,35.90,2022,8,34,...,None,None,None,None,None,None,0.0,0.0,0,None
4,19739464,2022-08-28,00274a69c705,3,5.0,35.90,179.50,2022,8,34,...,None,None,None,None,None,None,0.0,0.0,0,None

In [9]:
target_check = pd.read_sql(
    """
    SELECT
        COUNT(*) AS total_rows,
        COUNT(*) FILTER (WHERE quantity IS NULL) AS null_quantity,
        COUNT(*) FILTER (WHERE quantity < 0) AS negative_quantity,
        COUNT(*) FILTER (WHERE quantity = 0) AS zero_quantity,
        COUNT(*) FILTER (WHERE quantity > 0) AS positive_quantity,
        MIN(quantity) AS min_quantity,
        MAX(quantity) AS max_quantity,
        AVG(quantity) AS mean_quantity
    FROM analytics.price_sense_features;
    """,
    engine
)

print(target_check.to_string(index=False))

 total_rows  null_quantity  negative_quantity  zero_quantity  positive_quantity  min_quantity  max_quantity  mean_quantity
    7432685              0               1160           2438            7429087        -500.0        4952.0       5.642398

In [10]:
split_check = pd.read_sql(
    """
    SELECT
        CASE
            WHEN date <= '2023-12-31' THEN 'train'
            WHEN date <= '2024-06-30' THEN 'validation'
            ELSE 'test'
        END AS dataset,
        COUNT(*) AS row_count,
        MIN(date) AS min_date,
        MAX(date) AS max_date
    FROM analytics.price_sense_features
    GROUP BY 1
    ORDER BY 1;
    """,
    engine
)

print(split_check.to_string(index=False))

   dataset  row_count   min_date   max_date
      test    1199393 2024-07-01 2024-09-26
     train    3807606 2022-08-28 2023-12-31
validation    2425686 2024-01-01 2024-06-30

In [11]:
missing_check = pd.read_sql(
    """
    SELECT
        COUNT(*) AS total_rows,
        COUNT(*) FILTER (WHERE previous_price IS NULL) AS null_previous_price,
        COUNT(*) FILTER (WHERE quantity_lag_1 IS NULL) AS null_lag_1,
        COUNT(*) FILTER (WHERE quantity_lag_7 IS NULL) AS null_lag_7,
        COUNT(*) FILTER (WHERE quantity_lag_14 IS NULL) AS null_lag_14,
        COUNT(*) FILTER (WHERE quantity_lag_28 IS NULL) AS null_lag_28,
        COUNT(*) FILTER (WHERE demand_avg_7d IS NULL) AS null_avg_7d,
        COUNT(*) FILTER (WHERE demand_avg_28d IS NULL) AS null_avg_28d,
        COUNT(*) FILTER (WHERE demand_volatility_28d IS NULL) AS null_volatility,
        COUNT(*) FILTER (WHERE store_demand_avg_28d IS NULL) AS null_store_baseline
    FROM analytics.price_sense_features;
    """,
    engine
)

print(missing_check.to_string(index=False))

 total_rows  null_previous_price  null_lag_1  null_lag_7  null_lag_14  null_lag_28  null_avg_7d  null_avg_28d  null_volatility  null_store_baseline
    7432685                58027       58027      374205       697651      1258521        58027         58027           114078                 6658

In [12]:
categorical_missing = pd.read_sql(
    """
    SELECT
        COUNT(*) FILTER (WHERE dept_name IS NULL) AS null_dept_name,
        COUNT(*) FILTER (WHERE class_name IS NULL) AS null_class_name,
        COUNT(*) FILTER (WHERE subclass_name IS NULL) AS null_subclass_name,
        COUNT(*) FILTER (WHERE item_type IS NULL) AS null_item_type,
        COUNT(*) FILTER (WHERE division IS NULL) AS null_division,
        COUNT(*) FILTER (WHERE format IS NULL) AS null_format,
        COUNT(*) FILTER (WHERE city IS NULL) AS null_city
    FROM analytics.price_sense_features;
    """,
    engine
)

print(categorical_missing.to_string(index=False))

 null_dept_name  null_class_name  null_subclass_name  null_item_type  null_division  null_format  null_city
          36585            36585               36585          691370              0            0          0

In [13]:
numeric_missing = pd.read_sql(
    """
    SELECT
        COUNT(*) FILTER (WHERE price IS NULL) AS null_price,
        COUNT(*) FILTER (WHERE store_demand_avg_28d IS NULL) AS null_store_demand_avg,
        COUNT(*) FILTER (WHERE previous_price IS NULL) AS null_previous_price,
        COUNT(*) FILTER (WHERE discount_pct IS NULL) AS null_discount_pct,
        COUNT(*) FILTER (WHERE quantity_lag_1 IS NULL) AS null_lag_1,
        COUNT(*) FILTER (WHERE quantity_lag_7 IS NULL) AS null_lag_7,
        COUNT(*) FILTER (WHERE quantity_lag_14 IS NULL) AS null_lag_14,
        COUNT(*) FILTER (WHERE quantity_lag_28 IS NULL) AS null_lag_28,
        COUNT(*) FILTER (WHERE demand_avg_7d IS NULL) AS null_avg_7d,
        COUNT(*) FILTER (WHERE demand_avg_28d IS NULL) AS null_avg_28d,
        COUNT(*) FILTER (WHERE demand_volatility_28d IS NULL) AS null_volatility,
        COUNT(*) FILTER (WHERE demand_trend_7d IS NULL) AS null_trend,
        COUNT(*) FILTER (WHERE price_vs_previous_pct IS NULL) AS null_price_change,
        COUNT(*) FILTER (WHERE demand_momentum_7d IS NULL) AS null_momentum,
        COUNT(*) FILTER (WHERE demand_vs_baseline IS NULL) AS null_demand_baseline,
        COUNT(*) FILTER (WHERE promo_discount_interaction IS NULL) AS null_promo_discount,
        COUNT(*) FILTER (WHERE promo_price_change_interaction IS NULL) AS null_promo_price
    FROM analytics.price_sense_features;
    """,
    engine
)

print(numeric_missing.to_string(index=False))

 null_price  null_store_demand_avg  null_previous_price  null_discount_pct  null_lag_1  null_lag_7  null_lag_14  null_lag_28  null_avg_7d  null_avg_28d  null_volatility  null_trend  null_price_change  null_momentum  null_demand_baseline  null_promo_discount  null_promo_price
          0                   6658                58027            5920507       58027      374205       697651      1258521        58027         58027           114078       58027              65887          58132                  6658                    0                 0

In [14]:
target = "quantity"

categorical_features = [
    "dept_name",
    "class_name",
    "subclass_name",
    "item_type",
    "division",
    "format",
    "city"
]

numeric_features = [
    "price",
    "store_demand_avg_28d",
    "previous_price",
    "discount_pct",
    "quantity_lag_1",
    "quantity_lag_7",
    "quantity_lag_14",
    "quantity_lag_28",
    "demand_avg_7d",
    "demand_avg_28d",
    "demand_volatility_28d",
    "demand_trend_7d",
    "price_vs_previous_pct",
    "demand_momentum_7d",
    "demand_vs_baseline",
    "promo_discount_interaction",
    "promo_price_change_interaction",
    "markdown_pct",
    "year",
    "month",
    "week",
    "day_of_week",
    "is_weekend",
    "area"
]

print("Target:", target)
print("Categorical features:", len(categorical_features))
print("Numeric features:", len(numeric_features))
print("Total predictors:", len(categorical_features) + len(numeric_features))

Target: quantity
Categorical features: 7
Numeric features: 24
Total predictors: 31

In [15]:
feature_check = pd.read_sql(
    """
    SELECT column_name
    FROM information_schema.columns
    WHERE table_schema = 'analytics'
      AND table_name = 'price_sense_features';
    """,
    engine
)

available_columns = set(feature_check["column_name"])

missing_features = [
    col for col in categorical_features + numeric_features
    if col not in available_columns
]

print("Missing selected features:", missing_features)
print("All selected features exist:", len(missing_features) == 0)

Missing selected features: []
All selected features exist: True

In [16]:
split_sizes = pd.read_sql(
    f"""
    SELECT
        CASE
            WHEN date <= '2023-12-31' THEN 'train'
            WHEN date <= '2024-06-30' THEN 'validation'
            ELSE 'test'
        END AS dataset,
        COUNT(*) AS row_count
    FROM analytics.price_sense_features
    GROUP BY 1
    ORDER BY 1;
    """,
    engine
)

print(split_sizes.to_string(index=False))

   dataset  row_count
      test    1199393
     train    3807606
validation    2425686

In [17]:
model_columns = [
    target
] + categorical_features + numeric_features

model_query = f"""
SELECT
    {", ".join(model_columns)}
FROM analytics.price_sense_features
"""

print("Number of selected columns:", len(model_columns))
print("\nColumns:")
print(", ".join(model_columns))

Number of selected columns: 32

Columns:
quantity, dept_name, class_name, subclass_name, item_type, division, format, city, price, store_demand_avg_28d, previous_price, discount_pct, quantity_lag_1, quantity_lag_7, quantity_lag_14, quantity_lag_28, demand_avg_7d, demand_avg_28d, demand_volatility_28d, demand_trend_7d, price_vs_previous_pct, demand_momentum_7d, demand_vs_baseline, promo_discount_interaction, promo_price_change_interaction, markdown_pct, year, month, week, day_of_week, is_weekend, area

In [18]:
train_query = model_query + """
WHERE date <= '2023-12-31'
"""

train_chunks = pd.read_sql(
    train_query,
    engine,
    chunksize=800_000
)

print("Training data will be loaded in chunks of 800,000 rows.")

Training data will be loaded in chunks of 800,000 rows.

In [19]:
first_chunk = next(train_chunks)

print("Shape:", first_chunk.shape)
print("\nMemory usage:")
print(f"{first_chunk.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

print("\nData types:")
print(first_chunk.dtypes)

Shape: (800000, 32)

Memory usage:
281.41 MB

Data types:
quantity                          float64
dept_name                             str
class_name                            str
subclass_name                         str
item_type                             str
division                              str
format                                str
city                                  str
price                             float64
store_demand_avg_28d              float64
previous_price                    float64
discount_pct                      float64
quantity_lag_1                    float64
quantity_lag_7                    float64
quantity_lag_14                   float64
quantity_lag_28                   float64
demand_avg_7d                     float64
demand_avg_28d                    float64
demand_volatility_28d             float64
demand_trend_7d                   float64
price_vs_previous_pct             float64
demand_momentum_7d                float64
demand_vs_baseline                float64
promo_discount_interaction        float64
promo_price_change_interaction    float64
markdown_pct                      float64
year                                int64
month                               int64
week                                int64
day_of_week                         int64
is_weekend                          int64
area                                int64
dtype: object

In [20]:
for col in categorical_features:
    print(f"{col}: {first_chunk[col].nunique(dropna=False)} unique values")

dept_name: 178 unique values
class_name: 520 unique values
subclass_name: 753 unique values
item_type: 586 unique values
division: 2 unique values
format: 4 unique values
city: 3 unique values

In [21]:
full_cardinality = pd.read_sql(
    f"""
    SELECT
        COUNT(DISTINCT dept_name) AS dept_name,
        COUNT(DISTINCT class_name) AS class_name,
        COUNT(DISTINCT subclass_name) AS subclass_name,
        COUNT(DISTINCT item_type) AS item_type,
        COUNT(DISTINCT division) AS division,
        COUNT(DISTINCT format) AS format,
        COUNT(DISTINCT city) AS city
    FROM analytics.price_sense_features
    WHERE date <= '2023-12-31';
    """,
    engine
)

print(full_cardinality.to_string(index=False))

 dept_name  class_name  subclass_name  item_type  division  format  city
       178         526            770        594         2       4     3

In [22]:
train_categorical_missing = pd.read_sql(
    """
    SELECT
        COUNT(*) FILTER (WHERE dept_name IS NULL) AS null_dept_name,
        COUNT(*) FILTER (WHERE class_name IS NULL) AS null_class_name,
        COUNT(*) FILTER (WHERE subclass_name IS NULL) AS null_subclass_name,
        COUNT(*) FILTER (WHERE item_type IS NULL) AS null_item_type
    FROM analytics.price_sense_features
    WHERE date <= '2023-12-31';
    """,
    engine
)

print(train_categorical_missing.to_string(index=False))

 null_dept_name  null_class_name  null_subclass_name  null_item_type
           1227             1227                1227          360161

In [23]:
del first_chunk

print("First training chunk released from memory.")

First training chunk released from memory.

In [24]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

print("Preprocessing tools imported successfully.")

Preprocessing tools imported successfully.

In [25]:
from sklearn.pipeline import Pipeline

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="constant", fill_value="Unknown")),
    ("onehot", OneHotEncoder(
        handle_unknown="ignore",
        sparse_output=True
    ))
])

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

preprocessor = ColumnTransformer([
    ("categorical", categorical_pipeline, categorical_features),
    ("numeric", numeric_pipeline, numeric_features)
])

print("Preprocessing pipeline created.")

Preprocessing pipeline created.

In [26]:
print("scikit-learn version:", __import__("sklearn").__version__)
print("Pipeline ready:", preprocessor)

scikit-learn version: 1.9.1
Pipeline ready: ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(fill_value='Unknown',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['dept_name', 'class_name', 'subclass_name',
                                  'item_type', 'division', 'format', 'city']),
                                ('numeric',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median'))]),
                                 ['price', '...
                                  'previous_price', 'discount_pct',
                                  'quantity_lag_1', 'quantity_lag_7',
                                  'quantity_lag_14', 'quantity_lag_28',
                                  'demand_avg_7d', 'demand_avg_28d',
                                  'demand_volatility_28d', 'demand_trend_7d',
                                  'price_vs_previous_pct', 'demand_momentum_7d',
                                  'demand_vs_baseline',
                                  'promo_discount_interaction',
                                  'promo_price_change_interaction',
                                  'markdown_pct', 'year', 'month', 'week',
                                  'day_of_week', 'is_weekend', 'area'])])

In [27]:
median_query = """
SELECT
    percentile_cont(0.5) WITHIN GROUP (ORDER BY price) AS price,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY store_demand_avg_28d) AS store_demand_avg_28d,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY previous_price) AS previous_price,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY discount_pct) AS discount_pct,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY quantity_lag_1) AS quantity_lag_1,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY quantity_lag_7) AS quantity_lag_7,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY quantity_lag_14) AS quantity_lag_14,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY quantity_lag_28) AS quantity_lag_28,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY demand_avg_7d) AS demand_avg_7d,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY demand_avg_28d) AS demand_avg_28d,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY demand_volatility_28d) AS demand_volatility_28d,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY demand_trend_7d) AS demand_trend_7d,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY price_vs_previous_pct) AS price_vs_previous_pct,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY demand_momentum_7d) AS demand_momentum_7d,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY demand_vs_baseline) AS demand_vs_baseline,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY promo_discount_interaction) AS promo_discount_interaction,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY promo_price_change_interaction) AS promo_price_change_interaction,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY markdown_pct) AS markdown_pct,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY year) AS year,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY month) AS month,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY week) AS week,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY day_of_week) AS day_of_week,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY is_weekend) AS is_weekend,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY area) AS area
FROM analytics.price_sense_features
WHERE date <= '2023-12-31';
"""

training_medians = pd.read_sql(median_query, engine)

print(training_medians.to_string(index=False))

 price  store_demand_avg_28d  previous_price  discount_pct  quantity_lag_1  quantity_lag_7  quantity_lag_14  quantity_lag_28  demand_avg_7d  demand_avg_28d  demand_volatility_28d  demand_trend_7d  price_vs_previous_pct  demand_momentum_7d  demand_vs_baseline  promo_discount_interaction  promo_price_change_interaction  markdown_pct   year  month  week  day_of_week  is_weekend   area
  99.9          29123.136786            99.9      20.02002             2.0             2.0              2.0              2.0       2.285714        2.357143               1.502643              0.0                    0.0                 1.0            0.000151                         0.0                             0.0     41.092437 2023.0    9.0  35.0          4.0         0.0 1500.0

In [28]:
training_medians = training_medians.iloc[0].to_dict()

print("Training medians:")
for feature in numeric_features:
    print(f"{feature}: {training_medians[feature]}")

Training medians:
price: 99.9
store_demand_avg_28d: 29123.13678571428
previous_price: 99.9
discount_pct: 20.02002002002002
quantity_lag_1: 2.0
quantity_lag_7: 2.0
quantity_lag_14: 2.0
quantity_lag_28: 2.0
demand_avg_7d: 2.2857142857142856
demand_avg_28d: 2.357142857142857
demand_volatility_28d: 1.502643173856158
demand_trend_7d: 0.0
price_vs_previous_pct: 0.0
demand_momentum_7d: 1.0
demand_vs_baseline: 0.00015105602457552044
promo_discount_interaction: 0.0
promo_price_change_interaction: 0.0
markdown_pct: 41.09243697478992
year: 2023.0
month: 9.0
week: 35.0
day_of_week: 4.0
is_weekend: 0.0
area: 1500.0

In [29]:
numeric_fill_values = [
    training_medians[feature]
    for feature in numeric_features
]

numeric_fill_values

[99.9,
 29123.13678571428,
 99.9,
 20.02002002002002,
 2.0,
 2.0,
 2.0,
 2.0,
 2.2857142857142856,
 2.357142857142857,
 1.502643173856158,
 0.0,
 0.0,
 1.0,
 0.00015105602457552044,
 0.0,
 0.0,
 41.09243697478992,
 2023.0,
 9.0,
 35.0,
 4.0,
 0.0,
 1500.0]

In [30]:
category_values = {}

for col in categorical_features:
    query = f"""
        SELECT DISTINCT {col}
        FROM analytics.price_sense_features
        WHERE date <= '2023-12-31'
          AND {col} IS NOT NULL
        ORDER BY {col};
    """
    
    values = pd.read_sql(query, engine)[col].tolist()
    category_values[col] = values

    print(f"{col}: {len(values)} categories")

dept_name: 178 categories
class_name: 526 categories
subclass_name: 770 categories
item_type: 594 categories
division: 2 categories
format: 4 categories
city: 3 categories

In [31]:
for col in categorical_features:
    category_values[col].append("Unknown")

    print(
        f"{col}: {len(category_values[col])} categories "
        f"(including Unknown)"
    )

dept_name: 179 categories (including Unknown)
class_name: 527 categories (including Unknown)
subclass_name: 771 categories (including Unknown)
item_type: 595 categories (including Unknown)
division: 3 categories (including Unknown)
format: 5 categories (including Unknown)
city: 4 categories (including Unknown)

In [32]:
unknown_conflicts = {}

for col in categorical_features:
    exists = "Unknown" in category_values[col][:-1]
    unknown_conflicts[col] = exists

print(unknown_conflicts)

{'dept_name': False, 'class_name': False, 'subclass_name': False, 'item_type': False, 'division': False, 'format': False, 'city': False}

In [33]:
encoder = OneHotEncoder(
    categories=[category_values[col] for col in categorical_features],
    handle_unknown="ignore",
    sparse_output=True
)

print("OneHotEncoder created.")

OneHotEncoder created.

In [34]:
test_sample = pd.read_sql(
    model_query + """
    WHERE date <= '2023-12-31'
    LIMIT 1000
    """,
    engine
)

# Replace missing categorical values with "Unknown"
test_sample[categorical_features] = (
    test_sample[categorical_features]
    .fillna("Unknown")
)

# Replace missing numerical values with training medians
for col in numeric_features:
    test_sample[col] = test_sample[col].fillna(training_medians[col])

print("Sample shape:", test_sample.shape)
print("Missing values remaining:", test_sample.isna().sum().sum())

Sample shape: (1000, 32)
Missing values remaining: 0

In [35]:
encoded_sample = encoder.fit_transform(
    test_sample[categorical_features]
)

print("Encoded shape:", encoded_sample.shape)

Encoded shape: (1000, 2084)

In [36]:
for col, categories in zip(categorical_features, encoder.categories_):
    print(f"{col}: {len(categories)} encoded features")

dept_name: 179 encoded features
class_name: 527 encoded features
subclass_name: 771 encoded features
item_type: 595 encoded features
division: 3 encoded features
format: 5 encoded features
city: 4 encoded features

In [37]:
for col in categorical_features:
    rare_count = pd.read_sql(
        f"""
        SELECT COUNT(*) AS category_count
        FROM analytics.price_sense_features
        WHERE date <= '2023-12-31'
          AND {col} IS NOT NULL
        GROUP BY {col}
        HAVING COUNT(*) <= 10
        """,
        engine
    )["category_count"]

    print(
        f"{col}: "
        f"{len(rare_count)} categories occur <= 10 times"
    )

dept_name: 2 categories occur <= 10 times
class_name: 20 categories occur <= 10 times
subclass_name: 41 categories occur <= 10 times
item_type: 20 categories occur <= 10 times
division: 0 categories occur <= 10 times
format: 0 categories occur <= 10 times
city: 0 categories occur <= 10 times

In [38]:
for col in categorical_features:
    counts = pd.read_sql(
        f"""
        SELECT {col}, COUNT(*) AS n
        FROM analytics.price_sense_features
        WHERE date <= '2023-12-31'
          AND {col} IS NOT NULL
        GROUP BY {col}
        """,
        engine
    )

    print(
        f"{col}: "
        f"{(counts['n'] > 10).sum()} categories with >10 rows"
    )

dept_name: 176 categories with >10 rows
class_name: 506 categories with >10 rows
subclass_name: 729 categories with >10 rows
item_type: 574 categories with >10 rows
division: 2 categories with >10 rows
format: 4 categories with >10 rows
city: 3 categories with >10 rows

In [39]:
train_chunks = pd.read_sql(
    train_query,
    engine,
    chunksize=800_000
)

print("Training chunk iterator reset.")

Training chunk iterator reset.

In [40]:
chunk = next(train_chunks)

# Handle categorical missing values
chunk[categorical_features] = (
    chunk[categorical_features]
    .fillna("Unknown")
)

# Handle numerical missing values using training medians
for col in numeric_features:
    chunk[col] = chunk[col].fillna(training_medians[col])

# Encode categorical variables
X_cat = encoder.transform(
    chunk[categorical_features]
)

print("Chunk shape:", chunk.shape)
print("Encoded categorical shape:", X_cat.shape)
print(f"Sparse matrix memory: {(X_cat.data.nbytes + X_cat.indices.nbytes + X_cat.indptr.nbytes) / 1024**2:.2f} MB")

Chunk shape: (800000, 32)
Encoded categorical shape: (800000, 2084)
Sparse matrix memory: 67.14 MB

In [41]:
from scipy import sparse

X_num = sparse.csr_matrix(
    chunk[numeric_features].to_numpy(dtype=np.float64)
)

X_chunk = sparse.hstack(
    [X_cat, X_num],
    format="csr"
)

print("Final chunk matrix shape:", X_chunk.shape)
print(
    f"Sparse matrix memory: "
    f"{(X_chunk.data.nbytes + X_chunk.indices.nbytes + X_chunk.indptr.nbytes) / 1024**2:.2f} MB"
)

Final chunk matrix shape: (800000, 2108)
Sparse matrix memory: 258.76 MB

In [42]:
y_chunk = chunk[target].to_numpy(dtype=np.float64)

print("X shape:", X_chunk.shape)
print("y shape:", y_chunk.shape)
print("Target missing values:", np.isnan(y_chunk).sum())

X shape: (800000, 2108)
y shape: (800000,)
Target missing values: 0

In [43]:
X_train_parts = [X_chunk]
y_train_parts = [y_chunk]

for i, chunk in enumerate(train_chunks, start=2):
    chunk[categorical_features] = (
        chunk[categorical_features]
        .fillna("Unknown")
    )

    for col in numeric_features:
        chunk[col] = chunk[col].fillna(training_medians[col])

    X_cat = encoder.transform(
        chunk[categorical_features]
    )

    X_num = sparse.csr_matrix(
        chunk[numeric_features].to_numpy(dtype=np.float64)
    )

    X_part = sparse.hstack(
        [X_cat, X_num],
        format="csr"
    )

    y_part = chunk[target].to_numpy(dtype=np.float64)

    X_train_parts.append(X_part)
    y_train_parts.append(y_part)

    print(
        f"Chunk {i}: "
        f"X={X_part.shape}, "
        f"y={y_part.shape}"
    )

print("All training chunks processed.")

Chunk 2: X=(800000, 2108), y=(800000,)
Chunk 3: X=(800000, 2108), y=(800000,)
Chunk 4: X=(800000, 2108), y=(800000,)
Chunk 5: X=(607606, 2108), y=(607606,)
All training chunks processed.

In [44]:
X_train = sparse.vstack(
    X_train_parts,
    format="csr"
)

y_train = np.concatenate(
    y_train_parts
)

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print(
    f"X_train sparse memory: "
    f"{(X_train.data.nbytes + X_train.indices.nbytes + X_train.indptr.nbytes) / 1024**2:.2f} MB"
)

X_train shape: (3807606, 2108)
y_train shape: (3807606,)
X_train sparse memory: 1231.52 MB

In [45]:
from sklearn.linear_model import Ridge

print("Ridge imported successfully.")

Ridge imported successfully.

In [46]:
ridge_model = Ridge(
    alpha=1.0,
    solver="lsqr"
)

ridge_model.fit(X_train, y_train)

print("Ridge model fitted successfully.")

Ridge model fitted successfully.

In [47]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("Evaluation metrics imported successfully.")

Evaluation metrics imported successfully.

In [48]:
validation_query = model_query + """
WHERE date >= '2024-01-01'
  AND date <= '2024-06-30'
"""

validation_chunks = pd.read_sql(
    validation_query,
    engine,
    chunksize=800_000
)

print("Validation chunk iterator created.")

Validation chunk iterator created.

In [49]:
y_val_parts = []
y_pred_parts = []

for i, chunk in enumerate(validation_chunks, start=1):
    chunk[categorical_features] = (
        chunk[categorical_features]
        .fillna("Unknown")
    )

    for col in numeric_features:
        chunk[col] = chunk[col].fillna(training_medians[col])

    X_cat = encoder.transform(
        chunk[categorical_features]
    )

    X_num = sparse.csr_matrix(
        chunk[numeric_features].to_numpy(dtype=np.float64)
    )

    X_part = sparse.hstack(
        [X_cat, X_num],
        format="csr"
    )

    y_part = chunk[target].to_numpy(dtype=np.float64)

    predictions = ridge_model.predict(X_part)

    y_val_parts.append(y_part)
    y_pred_parts.append(predictions)

    print(
        f"Validation chunk {i}: "
        f"{len(y_part):,} rows processed"
    )

y_val = np.concatenate(y_val_parts)
y_pred = np.concatenate(y_pred_parts)

print("Validation processing complete.")

Validation chunk 1: 800,000 rows processed
Validation chunk 2: 800,000 rows processed
Validation chunk 3: 800,000 rows processed
Validation chunk 4: 25,686 rows processed
Validation processing complete.

In [50]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

validation_mae = mean_absolute_error(y_val, y_pred)
validation_rmse = np.sqrt(mean_squared_error(y_val, y_pred))
validation_r2 = r2_score(y_val, y_pred)

print(f"Validation MAE:  {validation_mae:.6f}")
print(f"Validation RMSE: {validation_rmse:.6f}")
print(f"Validation R²:   {validation_r2:.6f}")

Validation MAE:  2.359549
Validation RMSE: 7.735839
Validation R²:   0.916433

In [51]:
ridge_baseline = {
    "model": "Ridge",
    "alpha": 1.0,
    "validation_mae": validation_mae,
    "validation_rmse": validation_rmse,
    "validation_r2": validation_r2
}

print(ridge_baseline)

{'model': 'Ridge', 'alpha': 1.0, 'validation_mae': 2.3595491278828713, 'validation_rmse': np.float64(7.735839455847684), 'validation_r2': 0.9164334487857128}

In [52]:
from sklearn.linear_model import ElasticNet

print("ElasticNet imported successfully.")

ElasticNet imported successfully.

In [53]:
elastic_model = ElasticNet(
    alpha=0.001,
    l1_ratio=0.1,
    max_iter=100,
    tol=1e-3,
    random_state=42
)

elastic_model.fit(X_train, y_train)

print("ElasticNet model fitted successfully.")

ElasticNet model fitted successfully.

C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:786: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.382626e+08, tolerance: 2.572e+06
  model = cd_fast.sparse_enet_coordinate_descent(

In [54]:
print("ElasticNet convergence status: NOT CONVERGED")
print("Reason: max_iter=100 was reached before convergence.")
print("Decision: do not use this model for final comparison.")

ElasticNet convergence status: NOT CONVERGED
Reason: max_iter=100 was reached before convergence.
Decision: do not use this model for final comparison.

In [55]:
ridge_model_10 = Ridge(
    alpha=10.0,
    solver="lsqr"
)

ridge_model_10.fit(X_train, y_train)

print("Ridge(alpha=10) fitted successfully.")

Ridge(alpha=10) fitted successfully.

In [57]:
y_pred_ridge_10_parts = []

validation_chunks = pd.read_sql(
    validation_query,
    engine,
    chunksize=800_000
)

for i, chunk in enumerate(validation_chunks, start=1):
    chunk[categorical_features] = (
        chunk[categorical_features].fillna("Unknown")
    )

    chunk[numeric_features] = (
        chunk[numeric_features].fillna(
            pd.Series(numeric_fill_values, index=numeric_features)
        )
    )

    X_cat = encoder.transform(chunk[categorical_features])

    X_num = sparse.csr_matrix(
        chunk[numeric_features].to_numpy(dtype=np.float64)
    )

    X_part = sparse.hstack(
        [X_cat, X_num],
        format="csr"
    )

    y_pred_part = ridge_model_10.predict(X_part)
    y_pred_ridge_10_parts.append(y_pred_part)

    print(f"Validation chunk {i} processed: {len(chunk):,} rows")

y_pred_ridge_10 = np.concatenate(y_pred_ridge_10_parts)

print("\nRidge(alpha=10) validation predictions completed.")
print("Predictions:", len(y_pred_ridge_10))

Validation chunk 1 processed: 800,000 rows
Validation chunk 2 processed: 800,000 rows
Validation chunk 3 processed: 800,000 rows
Validation chunk 4 processed: 25,686 rows

Ridge(alpha=10) validation predictions completed.
Predictions: 2425686

In [58]:
ridge_10_mae = mean_absolute_error(y_val, y_pred_ridge_10)
ridge_10_rmse = np.sqrt(mean_squared_error(y_val, y_pred_ridge_10))
ridge_10_r2 = r2_score(y_val, y_pred_ridge_10)

print(f"Ridge(alpha=10) Validation MAE:  {ridge_10_mae:.6f}")
print(f"Ridge(alpha=10) Validation RMSE: {ridge_10_rmse:.6f}")
print(f"Ridge(alpha=10) Validation R²:   {ridge_10_r2:.6f}")

Ridge(alpha=10) Validation MAE:  2.359549
Ridge(alpha=10) Validation RMSE: 7.735839
Ridge(alpha=10) Validation R²:   0.916433

In [59]:
all_numeric_candidates = [
    "price",
    "year",
    "month",
    "week",
    "day_of_week",
    "is_weekend",
    "weight_volume",
    "weight_netto",
    "fatness",
    "area",
    "store_demand_avg_28d",
    "previous_price",
    "promotion_flag",
    "promo_type_code",
    "time_promo",
    "discount_pct",
    "quantity_lag_1",
    "quantity_lag_7",
    "quantity_lag_14",
    "quantity_lag_28",
    "demand_avg_7d",
    "demand_avg_28d",
    "demand_volatility_28d",
    "demand_trend_7d",
    "price_vs_previous_pct",
    "demand_momentum_7d",
    "demand_vs_baseline",
    "promo_discount_interaction",
    "promo_price_change_interaction",
    "markdown_flag",
    "markdown_pct"
]

print("Total numeric candidates:", len(all_numeric_candidates))
print("Currently selected:", len(numeric_features))

print("\nMissing from current model:")
print([x for x in all_numeric_candidates if x not in numeric_features])

Total numeric candidates: 31
Currently selected: 24

Missing from current model:
['weight_volume', 'weight_netto', 'fatness', 'promotion_flag', 'promo_type_code', 'time_promo', 'markdown_flag']

In [60]:
numeric_features_corrected = [
    "price",
    "year",
    "month",
    "week",
    "day_of_week",
    "is_weekend",
    "weight_volume",
    "weight_netto",
    "fatness",
    "area",
    "store_demand_avg_28d",
    "previous_price",
    "promotion_flag",
    "promo_type_code",
    "time_promo",
    "discount_pct",
    "quantity_lag_1",
    "quantity_lag_7",
    "quantity_lag_14",
    "quantity_lag_28",
    "demand_avg_7d",
    "demand_avg_28d",
    "demand_volatility_28d",
    "demand_trend_7d",
    "price_vs_previous_pct",
    "demand_momentum_7d",
    "promo_discount_interaction",
    "promo_price_change_interaction",
    "markdown_flag",
    "markdown_pct"
]

print("Corrected numeric features:", len(numeric_features_corrected))
print("Excluded leakage feature: demand_vs_baseline")

Corrected numeric features: 30
Excluded leakage feature: demand_vs_baseline

In [61]:
special_missing_features = [
    "discount_pct",
    "markdown_pct",
    "promotion_flag",
    "markdown_flag"
]

special_missing_query = f"""
SELECT
    COUNT(*) AS total_rows,
    COUNT(*) FILTER (WHERE discount_pct IS NULL) AS discount_nulls,
    COUNT(*) FILTER (WHERE markdown_pct IS NULL) AS markdown_nulls,
    COUNT(*) FILTER (WHERE promotion_flag = 0) AS no_promotion,
    COUNT(*) FILTER (WHERE markdown_flag = 0) AS no_markdown
FROM analytics.price_sense_features
WHERE date <= '2023-12-31';
"""

special_missing_check = pd.read_sql(
    special_missing_query,
    engine
)

print(special_missing_check.to_string(index=False))

 total_rows  discount_nulls  markdown_nulls  no_promotion  no_markdown
    3807606         3031868         3802507       3025981      3802507

In [62]:
special_zero_features = [
    "discount_pct",
    "markdown_pct"
]

corrected_numeric_fill_values = []

for feature in numeric_features_corrected:
    if feature in special_zero_features:
        corrected_numeric_fill_values.append(0.0)
    else:
        corrected_numeric_fill_values.append(
            training_medians[feature]
        )

corrected_numeric_fill_values = dict(
    zip(
        numeric_features_corrected,
        corrected_numeric_fill_values
    )
)

print("Special zero-filled features:")
print({
    feature: corrected_numeric_fill_values[feature]
    for feature in special_zero_features
})

print("\nTotal corrected numeric features:",
      len(corrected_numeric_fill_values))

KeyError: 'weight_volume'

In [63]:
corrected_medians_query = f"""
SELECT
    {", ".join(
        f"percentile_cont(0.5) WITHIN GROUP (ORDER BY {feature}) AS {feature}"
        for feature in numeric_features_corrected
        if feature not in ["discount_pct", "markdown_pct"]
    )}
FROM analytics.price_sense_features
WHERE date <= '2023-12-31';
"""

corrected_medians_df = pd.read_sql(
    corrected_medians_query,
    engine
)

corrected_training_medians = corrected_medians_df.iloc[0].to_dict()

for feature in special_zero_features:
    corrected_training_medians[feature] = 0.0

print("Corrected training medians calculated.")
print("Number of fill values:", len(corrected_training_medians))

Corrected training medians calculated.
Number of fill values: 30

In [64]:
for feature in numeric_features_corrected:
    print(
        f"{feature}: "
        f"{corrected_training_medians[feature]}"
    )

price: 99.9
year: 2023.0
month: 9.0
week: 35.0
day_of_week: 4.0
is_weekend: 0.0
weight_volume: 0.25
weight_netto: 0.22
fatness: 3.9
area: 1500.0
store_demand_avg_28d: 29123.13678571428
previous_price: 99.9
promotion_flag: 0.0
promo_type_code: 5.0
time_promo: 7.0
discount_pct: 0.0
quantity_lag_1: 2.0
quantity_lag_7: 2.0
quantity_lag_14: 2.0
quantity_lag_28: 2.0
demand_avg_7d: 2.2857142857142856
demand_avg_28d: 2.357142857142857
demand_volatility_28d: 1.502643173856158
demand_trend_7d: 0.0
price_vs_previous_pct: 0.0
demand_momentum_7d: 1.0
promo_discount_interaction: 0.0
promo_price_change_interaction: 0.0
markdown_flag: 0.0
markdown_pct: 0.0

In [65]:
del X_train
del X_train_parts
del y_train_parts

import gc
gc.collect()

print("Old training matrices cleared from memory.")

Old training matrices cleared from memory.

In [69]:
model_columns_corrected = (
    [target]
    + categorical_features
    + numeric_features_corrected
)

model_query_corrected = f"""
SELECT
    {", ".join(model_columns_corrected)}
FROM analytics.price_sense_features
"""

train_query_corrected = model_query_corrected + """
WHERE date <= '2023-12-31'
"""

print("Corrected model columns:", len(model_columns_corrected))
print("Corrected numeric features:", len(numeric_features_corrected))
print("Corrected categorical features:", len(categorical_features))
print(
    "Leakage feature included:",
    "demand_vs_baseline" in model_columns_corrected
)

Corrected model columns: 38
Corrected numeric features: 30
Corrected categorical features: 7
Leakage feature included: False

In [70]:
test_corrected_chunk = pd.read_sql(
    train_query_corrected + "\nLIMIT 5",
    engine
)

print("Shape:", test_corrected_chunk.shape)

missing_corrected = [
    col for col in model_columns_corrected
    if col not in test_corrected_chunk.columns
]

print("Missing corrected columns:", missing_corrected)

print("\nColumns:")
print(test_corrected_chunk.columns.tolist())

Shape: (5, 38)
Missing corrected columns: []

Columns:
['quantity', 'dept_name', 'class_name', 'subclass_name', 'item_type', 'division', 'format', 'city', 'price', 'year', 'month', 'week', 'day_of_week', 'is_weekend', 'weight_volume', 'weight_netto', 'fatness', 'area', 'store_demand_avg_28d', 'previous_price', 'promotion_flag', 'promo_type_code', 'time_promo', 'discount_pct', 'quantity_lag_1', 'quantity_lag_7', 'quantity_lag_14', 'quantity_lag_28', 'demand_avg_7d', 'demand_avg_28d', 'demand_volatility_28d', 'demand_trend_7d', 'price_vs_previous_pct', 'demand_momentum_7d', 'promo_discount_interaction', 'promo_price_change_interaction', 'markdown_flag', 'markdown_pct']

In [71]:
train_chunks = pd.read_sql(
    train_query_corrected,
    engine,
    chunksize=800_000
)

X_train_parts_corrected = []
y_train_parts_corrected = []

for i, chunk in enumerate(train_chunks, start=1):

    # Fill categorical missing values
    chunk[categorical_features] = (
        chunk[categorical_features].fillna("Unknown")
    )

    # Fill numeric missing values
    for feature in numeric_features_corrected:
        chunk[feature] = chunk[feature].fillna(
            corrected_training_medians[feature]
        )

    # One-hot encode categorical variables
    X_cat = encoder.transform(
        chunk[categorical_features]
    )

    # Numeric features
    X_num = sparse.csr_matrix(
        chunk[numeric_features_corrected].to_numpy(
            dtype=np.float64
        )
    )

    # Combine categorical + numeric
    X_part = sparse.hstack(
        [X_cat, X_num],
        format="csr"
    )

    y_part = chunk[target].to_numpy(
        dtype=np.float64
    )

    X_train_parts_corrected.append(X_part)
    y_train_parts_corrected.append(y_part)

    print(
        f"Training chunk {i} processed: "
        f"{len(chunk):,} rows"
    )

X_train_corrected = sparse.vstack(
    X_train_parts_corrected,
    format="csr"
)

y_train_corrected = np.concatenate(
    y_train_parts_corrected
)

print("\nCorrected training matrix created.")
print("X_train_corrected shape:", X_train_corrected.shape)
print("y_train_corrected shape:", y_train_corrected.shape)
print(
    "Sparse data memory:",
    f"{X_train_corrected.data.nbytes / (1024**2):.2f} MB"
)

Training chunk 1 processed: 800,000 rows
Training chunk 2 processed: 800,000 rows
Training chunk 3 processed: 800,000 rows
Training chunk 4 processed: 800,000 rows
Training chunk 5 processed: 607,606 rows

Corrected training matrix created.
X_train_corrected shape: (3807606, 2114)
y_train_corrected shape: (3807606,)
Sparse data memory: 881.38 MB

In [72]:
ridge_corrected = Ridge(
    alpha=1.0,
    solver="lsqr"
)

ridge_corrected.fit(
    X_train_corrected,
    y_train_corrected
)

print("Corrected Ridge(alpha=1) fitted successfully.")

Corrected Ridge(alpha=1) fitted successfully.

In [73]:
validation_query_corrected = model_query_corrected + """
WHERE date >= '2024-01-01'
  AND date <= '2024-06-30'
"""

print("Corrected validation query created.")

Corrected validation query created.

In [74]:
y_pred_corrected_parts = []

validation_chunks_corrected = pd.read_sql(
    validation_query_corrected,
    engine,
    chunksize=800_000
)

for i, chunk in enumerate(validation_chunks_corrected, start=1):

    # Categorical missing values
    chunk[categorical_features] = (
        chunk[categorical_features].fillna("Unknown")
    )

    # Correct numeric imputation
    for feature in numeric_features_corrected:
        chunk[feature] = chunk[feature].fillna(
            corrected_training_medians[feature]
        )

    # Transform categoricals
    X_cat = encoder.transform(
        chunk[categorical_features]
    )

    # Numeric matrix
    X_num = sparse.csr_matrix(
        chunk[numeric_features_corrected].to_numpy(
            dtype=np.float64
        )
    )

    # Combine
    X_part = sparse.hstack(
        [X_cat, X_num],
        format="csr"
    )

    # Predict
    y_pred_part = ridge_corrected.predict(X_part)

    y_pred_corrected_parts.append(y_pred_part)

    print(
        f"Validation chunk {i} processed: "
        f"{len(chunk):,} rows"
    )

y_pred_corrected = np.concatenate(
    y_pred_corrected_parts
)

print("\nCorrected validation predictions completed.")
print("Predictions:", len(y_pred_corrected))

Validation chunk 1 processed: 800,000 rows
Validation chunk 2 processed: 800,000 rows
Validation chunk 3 processed: 800,000 rows
Validation chunk 4 processed: 25,686 rows

Corrected validation predictions completed.
Predictions: 2425686

In [75]:
corrected_mae = mean_absolute_error(
    y_val,
    y_pred_corrected
)

corrected_rmse = np.sqrt(
    mean_squared_error(
        y_val,
        y_pred_corrected
    )
)

corrected_r2 = r2_score(
    y_val,
    y_pred_corrected
)

print(f"Corrected Ridge Validation MAE:  {corrected_mae:.6f}")
print(f"Corrected Ridge Validation RMSE: {corrected_rmse:.6f}")
print(f"Corrected Ridge Validation R²:   {corrected_r2:.6f}")

Corrected Ridge Validation MAE:  2.397499
Corrected Ridge Validation RMSE: 7.728365
Corrected Ridge Validation R²:   0.916595

In [76]:
ridge_corrected_10 = Ridge(
    alpha=10.0,
    solver="lsqr"
)

ridge_corrected_10.fit(
    X_train_corrected,
    y_train_corrected
)

print("Corrected Ridge(alpha=10) fitted successfully.")

Corrected Ridge(alpha=10) fitted successfully.

In [77]:
y_pred_corrected_10_parts = []

validation_chunks_corrected = pd.read_sql(
    validation_query_corrected,
    engine,
    chunksize=800_000
)

for i, chunk in enumerate(validation_chunks_corrected, start=1):

    chunk[categorical_features] = (
        chunk[categorical_features].fillna("Unknown")
    )

    for feature in numeric_features_corrected:
        chunk[feature] = chunk[feature].fillna(
            corrected_training_medians[feature]
        )

    X_cat = encoder.transform(
        chunk[categorical_features]
    )

    X_num = sparse.csr_matrix(
        chunk[numeric_features_corrected].to_numpy(
            dtype=np.float64
        )
    )

    X_part = sparse.hstack(
        [X_cat, X_num],
        format="csr"
    )

    y_pred_part = ridge_corrected_10.predict(X_part)

    y_pred_corrected_10_parts.append(y_pred_part)

    print(
        f"Validation chunk {i} processed: "
        f"{len(chunk):,} rows"
    )

y_pred_corrected_10 = np.concatenate(
    y_pred_corrected_10_parts
)

print("\nCorrected Ridge(alpha=10) predictions completed.")
print("Predictions:", len(y_pred_corrected_10))

Validation chunk 1 processed: 800,000 rows
Validation chunk 2 processed: 800,000 rows
Validation chunk 3 processed: 800,000 rows
Validation chunk 4 processed: 25,686 rows

Corrected Ridge(alpha=10) predictions completed.
Predictions: 2425686

In [78]:
corrected_10_mae = mean_absolute_error(
    y_val,
    y_pred_corrected_10
)

corrected_10_rmse = np.sqrt(
    mean_squared_error(
        y_val,
        y_pred_corrected_10
    )
)

corrected_10_r2 = r2_score(
    y_val,
    y_pred_corrected_10
)

print(f"Corrected Ridge(alpha=10) Validation MAE:  {corrected_10_mae:.6f}")
print(f"Corrected Ridge(alpha=10) Validation RMSE: {corrected_10_rmse:.6f}")
print(f"Corrected Ridge(alpha=10) Validation R²:   {corrected_10_r2:.6f}")

Corrected Ridge(alpha=10) Validation MAE:  2.397499
Corrected Ridge(alpha=10) Validation RMSE: 7.728365
Corrected Ridge(alpha=10) Validation R²:   0.916595

In [79]:
corrected_10_mae = mean_absolute_error(
    y_val,
    y_pred_corrected_10
)

corrected_10_rmse = np.sqrt(
    mean_squared_error(
        y_val,
        y_pred_corrected_10
    )
)

corrected_10_r2 = r2_score(
    y_val,
    y_pred_corrected_10
)

print(f"Corrected Ridge(alpha=10) Validation MAE:  {corrected_10_mae:.6f}")
print(f"Corrected Ridge(alpha=10) Validation RMSE: {corrected_10_rmse:.6f}")
print(f"Corrected Ridge(alpha=10) Validation R²:   {corrected_10_r2:.6f}")

Corrected Ridge(alpha=10) Validation MAE:  2.397499
Corrected Ridge(alpha=10) Validation RMSE: 7.728365
Corrected Ridge(alpha=10) Validation R²:   0.916595

In [80]:
del X_train_parts_corrected
del y_train_parts_corrected

import gc
gc.collect()

print("Redundant training chunks cleared.")
print(
    "Corrected training matrix still available:",
    X_train_corrected.shape
)

Redundant training chunks cleared.
Corrected training matrix still available: (3807606, 2114)

In [81]:
model_results = pd.DataFrame([
    {
        "model": "Ridge",
        "alpha": 1.0,
        "MAE": corrected_mae,
        "RMSE": corrected_rmse,
        "R2": corrected_r2
    },
    {
        "model": "Ridge",
        "alpha": 10.0,
        "MAE": corrected_10_mae,
        "RMSE": corrected_10_rmse,
        "R2": corrected_10_r2
    }
])

print(model_results.to_string(index=False))

model  alpha      MAE     RMSE       R2
Ridge    1.0 2.397499 7.728365 0.916595
Ridge   10.0 2.397499 7.728365 0.916595

In [82]:
from sklearn.linear_model import SGDRegressor

print("SGDRegressor imported successfully.")

SGDRegressor imported successfully.

In [83]:
sgd_model = SGDRegressor(
    loss="huber",
    penalty="l2",
    alpha=0.0001,
    max_iter=100,
    tol=1e-3,
    random_state=42
)

sgd_model.fit(
    X_train_corrected,
    y_train_corrected
)

print("SGDRegressor fitted successfully.")

SGDRegressor fitted successfully.

C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1620: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(

In [84]:
del sgd_model

import gc
gc.collect()

print("Non-converged SGD model cleared.")
print("Corrected Ridge training matrix remains available:")
print(X_train_corrected.shape)

Non-converged SGD model cleared.
Corrected Ridge training matrix remains available:
(3807606, 2114)

In [85]:
test_query_corrected = model_query_corrected + """
WHERE date >= '2024-07-01'
  AND date <= '2024-09-26'
"""

print("Corrected test query created.")

Corrected test query created.

In [86]:
y_test_parts = []

test_chunks_corrected = pd.read_sql(
    test_query_corrected,
    engine,
    chunksize=800_000
)

for i, chunk in enumerate(test_chunks_corrected, start=1):

    # Categorical missing values
    chunk[categorical_features] = (
        chunk[categorical_features].fillna("Unknown")
    )

    # Training-derived numeric imputation
    for feature in numeric_features_corrected:
        chunk[feature] = chunk[feature].fillna(
            corrected_training_medians[feature]
        )

    # Transform categoricals
    X_cat = encoder.transform(
        chunk[categorical_features]
    )

    # Numeric matrix
    X_num = sparse.csr_matrix(
        chunk[numeric_features_corrected].to_numpy(
            dtype=np.float64
        )
    )

    # Combine
    X_part = sparse.hstack(
        [X_cat, X_num],
        format="csr"
    )

    # Predict
    y_pred_part = ridge_corrected.predict(X_part)

    y_test_parts.append(y_pred_part)

    print(
        f"Test chunk {i} processed: "
        f"{len(chunk):,} rows"
    )

y_pred_test_corrected = np.concatenate(
    y_test_parts
)

print("\nCorrected test predictions completed.")
print("Predictions:", len(y_pred_test_corrected))

Test chunk 1 processed: 800,000 rows
Test chunk 2 processed: 399,393 rows

Corrected test predictions completed.
Predictions: 1199393

In [88]:
y_test = pd.read_sql(
    test_query_corrected,
    engine
)["quantity"].to_numpy(dtype=np.float64)

print("Actual test target rows:", len(y_test))
print("Test predictions rows:", len(y_pred_test_corrected))
print("Same length:", len(y_test) == len(y_pred_test_corrected))

Actual test target rows: 1199393
Test predictions rows: 1199393
Same length: True

In [89]:
test_mae = mean_absolute_error(
    y_test,
    y_pred_test_corrected
)

test_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        y_pred_test_corrected
    )
)

test_r2 = r2_score(
    y_test,
    y_pred_test_corrected
)

print(f"Corrected Ridge Test MAE:  {test_mae:.6f}")
print(f"Corrected Ridge Test RMSE: {test_rmse:.6f}")
print(f"Corrected Ridge Test R²:   {test_r2:.6f}")

Corrected Ridge Test MAE:  2.294340
Corrected Ridge Test RMSE: 8.237394
Corrected Ridge Test R²:   0.936059

In [90]:
final_model_results = pd.DataFrame([
    {
        "model": "Ridge",
        "alpha": 1.0,
        "validation_mae": corrected_mae,
        "validation_rmse": corrected_rmse,
        "validation_r2": corrected_r2,
        "test_mae": test_mae,
        "test_rmse": test_rmse,
        "test_r2": test_r2
    }
])

print(final_model_results.to_string(index=False))

model  alpha  validation_mae  validation_rmse  validation_r2  test_mae  test_rmse  test_r2
Ridge    1.0        2.397499         7.728365       0.916595   2.29434   8.237394 0.936059

In [91]:
elasticity_query = """
SELECT
    date,
    item_id,
    store_id,
    quantity,
    price,
    promotion_flag,
    discount_pct,
    markdown_flag,
    markdown_pct
FROM analytics.price_sense_features
WHERE date <= '2023-12-31'
"""

elasticity_sample = pd.read_sql(
    elasticity_query + "\nLIMIT 10",
    engine
)

print("Elasticity columns:")
print(elasticity_sample.columns.tolist())

print("\nSample shape:", elasticity_sample.shape)

Elasticity columns:
['date', 'item_id', 'store_id', 'quantity', 'price', 'promotion_flag', 'discount_pct', 'markdown_flag', 'markdown_pct']

Sample shape: (10, 9)

In [92]:
elasticity_variation_query = """
SELECT
    item_id,
    store_id,
    COUNT(*) AS observations,
    COUNT(DISTINCT price) AS unique_prices,
    MIN(price) AS min_price,
    MAX(price) AS max_price
FROM analytics.price_sense_features
WHERE date <= '2023-12-31'
  AND price > 0
GROUP BY item_id, store_id
"""

elasticity_variation = pd.read_sql(
    elasticity_variation_query,
    engine
)

print("Item-store pairs:", len(elasticity_variation))

print("\nPrice variation summary:")
print(
    elasticity_variation[
        ["observations", "unique_prices"]
    ].describe().to_string()
)

print(
    "\nPairs with >1 unique price:",
    (elasticity_variation["unique_prices"] > 1).sum()
)

Item-store pairs: 46156

Price variation summary:
       observations  unique_prices
count  46156.000000   46156.000000
mean      82.386320      23.412471
std      119.191865      46.182061
min        1.000000       1.000000
25%        7.000000       2.000000
50%       19.000000       7.000000
75%      111.000000      21.000000
max      491.000000     481.000000

Pairs with >1 unique price: 39030

In [93]:
elasticity_eligible = elasticity_variation[
    (elasticity_variation["observations"] >= 10)
    & (elasticity_variation["unique_prices"] >= 3)
].copy()

print(
    "Eligible item-store pairs:",
    len(elasticity_eligible)
)

print(
    "Percentage of all pairs:",
    f"{len(elasticity_eligible) / len(elasticity_variation) * 100:.2f}%"
)

print("\nEligible-pair summary:")
print(
    elasticity_eligible[
        ["observations", "unique_prices"]
    ].describe().to_string()
)

Eligible item-store pairs: 30062
Percentage of all pairs: 65.13%

Eligible-pair summary:
       observations  unique_prices
count  30062.000000   30062.000000
mean     123.368306      34.880347
std      130.189689      53.820529
min       10.000000       3.000000
25%       19.000000       7.000000
50%       66.500000      14.000000
75%      189.000000      38.000000
max      491.000000     481.000000

In [94]:
positive_quantity_query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(*) FILTER (WHERE quantity > 0) AS positive_quantity_rows,
    COUNT(*) FILTER (WHERE quantity <= 0) AS non_positive_quantity_rows
FROM analytics.price_sense_features
WHERE date <= '2023-12-31'
  AND price > 0;
"""

positive_quantity_check = pd.read_sql(
    positive_quantity_query,
    engine
)

print(positive_quantity_check.to_string(index=False))

 total_rows  positive_quantity_rows  non_positive_quantity_rows
    3802623                 3801844                         779

In [95]:
elasticity_query_positive = """
SELECT
    item_id,
    store_id,
    quantity,
    price,
    promotion_flag,
    markdown_flag
FROM analytics.price_sense_features
WHERE date <= '2023-12-31'
  AND price > 0
  AND quantity > 0
"""

elasticity_chunks = pd.read_sql(
    elasticity_query_positive,
    engine,
    chunksize=800_000
)

print("Elasticity query created.")

Elasticity query created.

In [96]:
elasticity_parts = []

for i, chunk in enumerate(elasticity_chunks, start=1):
    elasticity_parts.append(chunk)

    print(
        f"Elasticity chunk {i} loaded: "
        f"{len(chunk):,} rows"
    )

elasticity_data = pd.concat(
    elasticity_parts,
    ignore_index=True
)

print("\nElasticity data loaded.")
print("Rows:", len(elasticity_data))
print("Columns:", elasticity_data.shape[1])

Elasticity chunk 1 loaded: 800,000 rows
Elasticity chunk 2 loaded: 800,000 rows
Elasticity chunk 3 loaded: 800,000 rows
Elasticity chunk 4 loaded: 800,000 rows
Elasticity chunk 5 loaded: 601,844 rows

Elasticity data loaded.
Rows: 3801844
Columns: 6

In [97]:
eligible_keys = elasticity_eligible[
    ["item_id", "store_id"]
].copy()

elasticity_data = elasticity_data.merge(
    eligible_keys,
    on=["item_id", "store_id"],
    how="inner"
)

print("Rows after eligible-pair filter:", len(elasticity_data))
print(
    "Unique eligible item-store pairs:",
    elasticity_data[["item_id", "store_id"]]
    .drop_duplicates()
    .shape[0]
)

Rows after eligible-pair filter: 3708052
Unique eligible item-store pairs: 30062

In [98]:
elasticity_results = []

for (item_id, store_id), group in elasticity_data.groupby(
    ["item_id", "store_id"],
    sort=False
):
    if len(group) < 10:
        continue

    log_price = np.log(group["price"].to_numpy(dtype=np.float64))
    log_quantity = np.log(group["quantity"].to_numpy(dtype=np.float64))

    promotion = group["promotion_flag"].to_numpy(dtype=np.float64)
    markdown = group["markdown_flag"].to_numpy(dtype=np.float64)

    X = np.column_stack([
        np.ones(len(group)),
        log_price,
        promotion,
        markdown
    ])

    try:
        coefficients, _, _, _ = np.linalg.lstsq(
            X,
            log_quantity,
            rcond=None
        )

        predictions = X @ coefficients

        ss_res = np.sum(
            (log_quantity - predictions) ** 2
        )

        ss_tot = np.sum(
            (log_quantity - log_quantity.mean()) ** 2
        )

        r2 = (
            1 - ss_res / ss_tot
            if ss_tot > 0
            else np.nan
        )

        elasticity_results.append({
            "item_id": item_id,
            "store_id": store_id,
            "observations": len(group),
            "elasticity": coefficients[1],
            "promotion_effect": coefficients[2],
            "markdown_effect": coefficients[3],
            "r2": r2
        })

    except np.linalg.LinAlgError:
        continue

elasticity_results = pd.DataFrame(
    elasticity_results
)

print("Elasticity estimates:", len(elasticity_results))
print(
    "Mean elasticity:",
    elasticity_results["elasticity"].mean()
)
print(
    "Median elasticity:",
    elasticity_results["elasticity"].median()
)

Elasticity estimates: 30060
Mean elasticity: -2.5892677082582165
Median elasticity: -0.3037360949678495

In [99]:
print("Elasticity quantiles:")
print(
    elasticity_results["elasticity"]
    .quantile([0, 0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99, 1.00])
    .to_string()
)

print("\nNegative elasticity estimates:",
      (elasticity_results["elasticity"] < 0).sum())

print("Positive elasticity estimates:",
      (elasticity_results["elasticity"] >= 0).sum())

print("\nR² quantiles:")
print(
    elasticity_results["r2"]
    .quantile([0, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99, 1.00])
    .to_string()
)

Elasticity quantiles:
0.00   -21857.637908
0.01      -38.730369
0.05       -8.441715
0.25       -1.196168
0.50       -0.303736
0.75        0.186643
0.95        2.838070
0.99       11.116671
1.00    21875.120697

Negative elasticity estimates: 19169
Positive elasticity estimates: 10891

R² quantiles:
0.00    1.172189e-10
0.25    1.164519e-02
0.50    4.597278e-02
0.75    1.410012e-01
0.90    3.116953e-01
0.95    4.389374e-01
0.99    6.971530e-01
1.00    1.000000e+00

In [100]:
elasticity_filtered = elasticity_results[
    (elasticity_results["elasticity"] < 0)
    & (elasticity_results["elasticity"] > -5)
    & (elasticity_results["r2"] >= 0.05)
].copy()

print(
    "Filtered elasticity estimates:",
    len(elasticity_filtered)
)

print(
    "Percentage retained:",
    f"{len(elasticity_filtered) / len(elasticity_results) * 100:.2f}%"
)

print("\nFiltered elasticity summary:")
print(
    elasticity_filtered[
        ["elasticity", "r2", "observations"]
    ].describe().to_string()
)

Filtered elasticity estimates: 8939
Percentage retained: 29.74%

Filtered elasticity summary:
         elasticity           r2  observations
count  8.939000e+03  8939.000000   8939.000000
mean  -1.295636e+00     0.213863    144.890927
std    1.057865e+00     0.170243    134.781896
min   -4.989584e+00     0.050026     10.000000
25%   -1.814236e+00     0.086972     30.000000
50%   -9.913967e-01     0.153591     97.000000
75%   -4.992187e-01     0.288093    231.000000
max   -2.372780e-17     1.000000    491.000000

In [101]:
elasticity_filtered["elasticity_band"] = pd.cut(
    elasticity_filtered["elasticity"],
    bins=[-5, -2, -1, -0.5, 0],
    labels=[
        "Highly elastic (< -2)",
        "Elastic (-2 to -1)",
        "Moderately elastic (-1 to -0.5)",
        "Weakly elastic (-0.5 to 0)"
    ],
    include_lowest=True
)

elasticity_band_summary = (
    elasticity_filtered["elasticity_band"]
    .value_counts()
    .sort_index()
)

print(elasticity_band_summary)
print(
    "\nPercentages:"
)
print(
    (elasticity_band_summary / len(elasticity_filtered) * 100)
    .round(2)
)

elasticity_band
Highly elastic (< -2)              1928
Elastic (-2 to -1)                 2501
Moderately elastic (-1 to -0.5)    2267
Weakly elastic (-0.5 to 0)         2243
Name: count, dtype: int64

Percentages:
elasticity_band
Highly elastic (< -2)              21.57
Elastic (-2 to -1)                 27.98
Moderately elastic (-1 to -0.5)    25.36
Weakly elastic (-0.5 to 0)         25.09
Name: count, dtype: float64

In [102]:
elasticity_filtered.to_csv(
    "pricesense_elasticity.csv",
    index=False
)

print("Elasticity results saved.")
print("Rows saved:", len(elasticity_filtered))

Elasticity results saved.
Rows saved: 8939

In [105]:
pricing_base_query = """
SELECT DISTINCT ON (item_id, store_id)
    item_id,
    store_id,
    date,
    quantity AS current_demand,
    price AS current_price
FROM analytics.price_sense_features
WHERE date >= '2024-07-01'
  AND date <= '2024-09-26'
  AND price > 0
ORDER BY item_id, store_id, date DESC
"""

pricing_base = pd.read_sql(pricing_base_query, engine)

pricing_base = pricing_base.merge(
    elasticity_filtered[["item_id", "store_id", "elasticity"]],
    on=["item_id", "store_id"],
    how="inner"
)

print("Pricing base rows:", len(pricing_base))
print("\nMissing values:")
print(pricing_base.isna().sum())

print("\nSample:")
print(pricing_base.head())

Pricing base rows: 5829

Missing values:
item_id           0
store_id          0
date              0
current_demand    0
current_price     0
elasticity        0
dtype: int64

Sample:
        item_id  store_id        date  current_demand  current_price  \
0  001829cb707d         1  2024-09-26             1.0         149.90
1  001829cb707d         2  2024-09-25             2.0         142.41
2  00274a69c705         4  2024-09-26             2.0          35.90
3  002f51c34a7a         1  2024-09-26             6.0          97.90
4  004c615c8f87         1  2024-09-20             1.0         369.00

   elasticity
0   -0.191222
1   -1.221127
2   -1.322994
3   -1.273648
4   -1.855222

In [106]:
price_changes = [-0.10, -0.05, 0.00, 0.05, 0.10]

simulation_rows = []

for change in price_changes:
    scenario = pricing_base.copy()

    scenario["price_change_pct"] = change * 100
    scenario["simulated_price"] = (
        scenario["current_price"] * (1 + change)
    )

    scenario["simulated_demand"] = (
        scenario["current_demand"]
        * (
            scenario["simulated_price"]
            / scenario["current_price"]
        ) ** scenario["elasticity"]
    )

    scenario["simulated_revenue"] = (
        scenario["simulated_price"]
        * scenario["simulated_demand"]
    )

    simulation_rows.append(scenario)

pricing_simulation = pd.concat(
    simulation_rows,
    ignore_index=True
)

print("Simulation rows:", len(pricing_simulation))
print("\nPrice scenarios:")
print(
    pricing_simulation["price_change_pct"]
    .value_counts()
    .sort_index()
)

print("\nSample:")
print(pricing_simulation.head())

Simulation rows: 29145

Price scenarios:
price_change_pct
-10.0    5829
-5.0     5829
 0.0     5829
 5.0     5829
 10.0    5829
Name: count, dtype: int64

Sample:
        item_id  store_id        date  current_demand  current_price  \
0  001829cb707d         1  2024-09-26             1.0         149.90
1  001829cb707d         2  2024-09-25             2.0         142.41
2  00274a69c705         4  2024-09-26             2.0          35.90
3  002f51c34a7a         1  2024-09-26             6.0          97.90
4  004c615c8f87         1  2024-09-20             1.0         369.00

   elasticity  price_change_pct  simulated_price  simulated_demand  \
0   -0.191222             -10.0          134.910          1.020352
1   -1.221127             -10.0          128.169          2.274604
2   -1.322994             -10.0           32.310          2.299148
3   -1.273648             -10.0           88.110          6.861676
4   -1.855222             -10.0          332.100          1.215879

   simulated_revenue
0         137.655625
1         291.533662
2          74.285461
3         604.582262
4         403.793349

In [107]:
scenario_summary = (
    pricing_simulation
    .groupby("price_change_pct")
    .agg(
        avg_price=("simulated_price", "mean"),
        avg_demand=("simulated_demand", "mean"),
        total_revenue=("simulated_revenue", "sum"),
        avg_revenue=("simulated_revenue", "mean")
    )
    .reset_index()
    .sort_values("price_change_pct")
)

print(scenario_summary.to_string(index=False))

 price_change_pct  avg_price  avg_demand  total_revenue  avg_revenue
            -10.0 244.760311    4.338389   3.675420e+06   630.540370
             -5.0 258.358106    3.944843   3.533828e+06   606.249400
              0.0 271.955902    3.617433   3.417915e+06   586.363881
              5.0 285.553697    3.341560   3.322385e+06   569.975127
             10.0 299.151492    3.106472   3.243243e+06   556.397795

In [108]:
pricing_recommendations = (
    pricing_simulation
    .sort_values(
        ["item_id", "store_id", "simulated_revenue"],
        ascending=[True, True, False]
    )
    .drop_duplicates(
        subset=["item_id", "store_id"],
        keep="first"
    )
    .copy()
)

pricing_recommendations["revenue_change_pct"] = (
    (
        pricing_recommendations["simulated_revenue"]
        / (
            pricing_recommendations["current_price"]
            * pricing_recommendations["current_demand"]
        )
    ) - 1
) * 100

print("Recommendations:", len(pricing_recommendations))

print("\nRecommended price changes:")
print(
    pricing_recommendations["price_change_pct"]
    .value_counts()
    .sort_index()
)

print("\nSample recommendations:")
print(
    pricing_recommendations[
        [
            "item_id",
            "store_id",
            "current_price",
            "elasticity",
            "price_change_pct",
            "simulated_price",
            "simulated_demand",
            "simulated_revenue",
            "revenue_change_pct"
        ]
    ].head(10)
)

Recommendations: 5829

Recommended price changes:
price_change_pct
-10.0    2988
 10.0    2841
Name: count, dtype: int64

Sample recommendations:
            item_id  store_id  current_price  elasticity  price_change_pct  \
23316  001829cb707d         1         149.90   -0.191222              10.0
1      001829cb707d         2         142.41   -1.221127             -10.0
2      00274a69c705         4          35.90   -1.322994             -10.0
3      002f51c34a7a         1          97.90   -1.273648             -10.0
4      004c615c8f87         1         369.00   -1.855222             -10.0
5      005addd8096b         2          79.90   -1.483608             -10.0
6      005d50e1f4fa         1         411.38   -2.183055             -10.0
7      0063a7918c2c         1         369.90   -1.932149             -10.0
23324  0063a7918c2c         2         469.90   -0.928335              10.0
9      0063a7918c2c         4         499.90   -2.165796             -10.0

       simulated_price  simulated_demand  simulated_revenue  \
23316          164.890          0.981940         161.912039
1              128.169          2.274604         291.533662
2               32.310          2.299148          74.285461
3               88.110          6.861676         604.582262
4              332.100          1.215879         403.793349
5               71.910          1.169193          84.076660
6              370.242          2.660701         985.103291
7              332.910          2.451547         816.144617
23324          516.890          1.830643         946.241176
9              449.910          1.256323         565.232360

       revenue_change_pct
23316            8.013368
1                2.357160
2                3.461645
3                2.925138
4                9.429092
5                5.227359
6               13.274881
7               10.319629
23324            0.685377
9               13.069086

In [109]:
current_revenue = (
    pricing_recommendations["current_price"]
    * pricing_recommendations["current_demand"]
)

pricing_impact = pd.DataFrame({
    "current_revenue": current_revenue,
    "recommended_revenue": pricing_recommendations["simulated_revenue"],
    "revenue_change_pct": pricing_recommendations["revenue_change_pct"]
})

print("Average revenue change:",
      pricing_impact["revenue_change_pct"].mean())

print("Median revenue change:",
      pricing_impact["revenue_change_pct"].median())

print("Minimum revenue change:",
      pricing_impact["revenue_change_pct"].min())

print("Maximum revenue change:",
      pricing_impact["revenue_change_pct"].max())

print("\nRecommendations with positive revenue change:",
      (pricing_impact["revenue_change_pct"] > 0).sum())

print("Recommendations with negative revenue change:",
      (pricing_impact["revenue_change_pct"] < 0).sum())

Average revenue change: 9.001308718006003
Median revenue change: 5.9730227024719085
Minimum revenue change: 0.0012012357891721948
Maximum revenue change: 52.22817077536413

Recommendations with positive revenue change: 5829
Recommendations with negative revenue change: 0

In [110]:
print("X_train_corrected:", X_train_corrected.shape)
print("y_train_corrected:", y_train_corrected.shape)

print("\nAvailable objects:")
for name in [
    "X_train_corrected",
    "y_train_corrected",
    "ridge_corrected",
    "ridge_corrected_10"
]:
    print(f"{name}: {'YES' if name in globals() else 'NO'}")

X_train_corrected: (3807606, 2114)
y_train_corrected: (3807606,)

Available objects:
X_train_corrected: YES
y_train_corrected: YES
ridge_corrected: YES
ridge_corrected_10: YES

In [111]:
from scipy import sparse

sample_size = 500_000

rng = np.random.default_rng(42)

sample_indices = rng.choice(
    X_train_corrected.shape[0],
    size=sample_size,
    replace=False
)

X_train_sample = X_train_corrected[sample_indices]
y_train_sample = y_train_corrected[sample_indices]

print("Sample X shape:", X_train_sample.shape)
print("Sample y shape:", y_train_sample.shape)
print("Sparse matrix:", sparse.issparse(X_train_sample))

Sample X shape: (500000, 2114)
Sample y shape: (500000,)
Sparse matrix: True

In [112]:
numeric_indices = [
    2084 + i for i in range(len(numeric_features_corrected))
]

X_train_numeric_sample = X_train_sample[:, numeric_indices].toarray()

print("Numeric sample shape:", X_train_numeric_sample.shape)
print("Memory (MB):", round(
    X_train_numeric_sample.nbytes / (1024**2), 2
))

Numeric sample shape: (500000, 30)
Memory (MB): 114.44

In [113]:
from sklearn.ensemble import HistGradientBoostingRegressor

hist_model = HistGradientBoostingRegressor(
    max_iter=150,
    learning_rate=0.08,
    max_leaf_nodes=31,
    l2_regularization=1.0,
    random_state=42
)

hist_model.fit(
    X_train_numeric_sample,
    y_train_sample
)

print("HistGradientBoosting training complete.")

HistGradientBoosting training complete.

In [115]:
train_medians = {
    "price": 99.9,
    "year": 2023.0,
    "month": 9.0,
    "week": 35.0,
    "day_of_week": 4.0,
    "is_weekend": 0.0,
    "weight_volume": 0.25,
    "weight_netto": 0.22,
    "fatness": 3.9,
    "area": 1500.0,
    "store_demand_avg_28d": 29123.13678571428,
    "previous_price": 99.9,
    "promotion_flag": 0.0,
    "promo_type_code": 5.0,
    "time_promo": 7.0,
    "discount_pct": 0.0,
    "quantity_lag_1": 2.0,
    "quantity_lag_7": 2.0,
    "quantity_lag_14": 2.0,
    "quantity_lag_28": 2.0,
    "demand_avg_7d": 2.2857142857142856,
    "demand_avg_28d": 2.357142857142857,
    "demand_volatility_28d": 1.502643173856158,
    "demand_trend_7d": 0.0,
    "price_vs_previous_pct": 0.0,
    "demand_momentum_7d": 1.0,
    "promo_discount_interaction": 0.0,
    "promo_price_change_interaction": 0.0,
    "markdown_flag": 0.0,
    "markdown_pct": 0.0
}

validation_numeric_parts = []

for chunk in pd.read_sql(
    validation_numeric_query,
    engine,
    chunksize=800_000
):
    chunk = chunk.copy()

    for col in numeric_features_corrected:
        if col in ["discount_pct", "markdown_pct"]:
            chunk[col] = chunk[col].fillna(0)
        else:
            chunk[col] = chunk[col].fillna(train_medians[col])

    validation_numeric_parts.append(
        chunk[numeric_features_corrected]
    )

X_val_numeric = pd.concat(
    validation_numeric_parts,
    ignore_index=True
).to_numpy(dtype=np.float64)

print("Validation shape:", X_val_numeric.shape)
print("Memory (MB):", round(
    X_val_numeric.nbytes / (1024**2), 2
))

Validation shape: (2425686, 30)
Memory (MB): 555.2

In [116]:
hist_predictions = hist_model.predict(X_val_numeric)

hist_mae = mean_absolute_error(
    y_val,
    hist_predictions
)

hist_rmse = np.sqrt(
    mean_squared_error(
        y_val,
        hist_predictions
    )
)

hist_r2 = r2_score(
    y_val,
    hist_predictions
)

print("HistGradientBoosting Validation Results")
print("---------------------------------------")
print("MAE :", hist_mae)
print("RMSE:", hist_rmse)
print("R²  :", hist_r2)

HistGradientBoosting Validation Results
---------------------------------------
MAE : 2.245065916970659
RMSE: 9.097360165977982
R²  : 0.8844291358361885

In [117]:
from sklearn.linear_model import Ridge

ridge_numeric = Ridge(
    alpha=1.0,
    solver="lsqr"
)

ridge_numeric.fit(
    X_train_numeric_sample,
    y_train_sample
)

print("Numeric-only Ridge training complete.")

Numeric-only Ridge training complete.

In [118]:
ridge_numeric_predictions = ridge_numeric.predict(X_val_numeric)

ridge_numeric_mae = mean_absolute_error(
    y_val,
    ridge_numeric_predictions
)

ridge_numeric_rmse = np.sqrt(
    mean_squared_error(
        y_val,
        ridge_numeric_predictions
    )
)

ridge_numeric_r2 = r2_score(
    y_val,
    ridge_numeric_predictions
)

print("Numeric-only Ridge Validation Results")
print("-------------------------------------")
print("MAE :", ridge_numeric_mae)
print("RMSE:", ridge_numeric_rmse)
print("R²  :", ridge_numeric_r2)

Numeric-only Ridge Validation Results
-------------------------------------
MAE : 2.427907296388191
RMSE: 7.848620710816767
R²  : 0.9139790435476911

In [120]:
%pip install xgboost
import xgboost as xgb

print("XGBoost version:", xgb.__version__)

Collecting xgboost
  Downloading xgboost-3.4.1-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in C:\Users\ADMIN\anaconda3\Lib\site-packages (from xgboost) (2.4.6)
Requirement already satisfied: scipy in C:\Users\ADMIN\anaconda3\Lib\site-packages (from xgboost) (1.18.1)
Downloading xgboost-3.4.1-py3-none-win_amd64.whl (48.9 MB)
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---- ----------------------------------- 5.8/48.9 MB 32.1 MB/s eta 0:00:02
   ----------- ---------------------------- 13.9/48.9 MB 34.2 MB/s eta 0:00:02
   ----------------- ---------------------- 22.0/48.9 MB 36.4 MB/s eta 0:00:01
   ------------------------ --------------- 30.1/48.9 MB 37.0 MB/s eta 0:00:01
   ------------------------------- -------- 38.3/48.9 MB 37.7 MB/s eta 0:00:01
   -------------------------------------- - 47.4/48.9 MB 38.4 MB/s eta 0:00:01
   ---------------------------------------  48.8/48.9 MB 38.4 MB/s eta 0:00:01
   ---------------------------------------- 48.9/48.9 MB 32.8 MB/s  0:00:01
Installing collected packages: xgboost
Successfully installed xgboost-3.4.1
Note: you may need to restart the kernel to use updated packages.
XGBoost version: 3.4.1

In [121]:
from xgboost import XGBRegressor

xgb_model = XGBRegressor(
    n_estimators=200,
    max_depth=8,
    learning_rate=0.08,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    eval_metric="rmse",
    tree_method="hist",
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(
    X_train_numeric_sample,
    y_train_sample,
    verbose=False
)

print("XGBoost training complete.")

XGBoost training complete.

In [122]:
xgb_predictions = xgb_model.predict(X_val_numeric)

xgb_mae = mean_absolute_error(
    y_val,
    xgb_predictions
)

xgb_rmse = np.sqrt(
    mean_squared_error(
        y_val,
        xgb_predictions
    )
)

xgb_r2 = r2_score(
    y_val,
    xgb_predictions
)

print("XGBoost Validation Results")
print("--------------------------")
print("MAE :", xgb_mae)
print("RMSE:", xgb_rmse)
print("R²  :", xgb_r2)

XGBoost Validation Results
--------------------------
MAE : 2.2202815020433517
RMSE: 8.943184465586139
R²  : 0.8883131710389119

In [123]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=100,
    max_depth=12,
    min_samples_leaf=5,
    max_features="sqrt",
    random_state=42,
    n_jobs=-1
)

rf_model.fit(
    X_train_numeric_sample,
    y_train_sample
)

print("Random Forest training complete.")

Random Forest training complete.

In [124]:
rf_predictions = rf_model.predict(X_val_numeric)

rf_mae = mean_absolute_error(
    y_val,
    rf_predictions
)

rf_rmse = np.sqrt(
    mean_squared_error(
        y_val,
        rf_predictions
    )
)

rf_r2 = r2_score(
    y_val,
    rf_predictions
)

print("Random Forest Validation Results")
print("--------------------------------")
print("MAE :", rf_mae)
print("RMSE:", rf_rmse)
print("R²  :", rf_r2)

Random Forest Validation Results
--------------------------------
MAE : 2.217600574980949
RMSE: 7.17506068609758
R²  : 0.9281099575129821

In [125]:
X_train_numeric = X_train_corrected[:, numeric_indices].toarray()

print("Full numeric training shape:", X_train_numeric.shape)
print(
    "Memory (MB):",
    round(X_train_numeric.nbytes / (1024**2), 2)
)

Full numeric training shape: (3807606, 30)
Memory (MB): 871.49

In [126]:
rf_full_model = RandomForestRegressor(
    n_estimators=50,
    max_depth=12,
    min_samples_leaf=5,
    max_features="sqrt",
    random_state=42,
    n_jobs=-1
)

rf_full_model.fit(
    X_train_numeric,
    y_train_corrected
)

print("Full-data Random Forest training complete.")

Full-data Random Forest training complete.

In [127]:
rf_full_predictions = rf_full_model.predict(X_val_numeric)

rf_full_mae = mean_absolute_error(
    y_val,
    rf_full_predictions
)

rf_full_rmse = np.sqrt(
    mean_squared_error(
        y_val,
        rf_full_predictions
    )
)

rf_full_r2 = r2_score(
    y_val,
    rf_full_predictions
)

print("Full-data Random Forest Validation Results")
print("------------------------------------------")
print("MAE :", rf_full_mae)
print("RMSE:", rf_full_rmse)
print("R²  :", rf_full_r2)

Full-data Random Forest Validation Results
------------------------------------------
MAE : 2.2175978201310316
RMSE: 7.132157556751232
R²  : 0.9289671172355917

In [128]:
test_numeric_query = f"""
SELECT
    {", ".join(numeric_features_corrected)}
FROM analytics.price_sense_features
WHERE date >= '2024-07-01'
  AND date <= '2024-09-26'
"""

test_numeric_parts = []

for chunk in pd.read_sql(
    test_numeric_query,
    engine,
    chunksize=800_000
):
    chunk = chunk.copy()

    for col in numeric_features_corrected:
        if col in ["discount_pct", "markdown_pct"]:
            chunk[col] = chunk[col].fillna(0)
        else:
            chunk[col] = chunk[col].fillna(train_medians[col])

    test_numeric_parts.append(
        chunk[numeric_features_corrected]
    )

X_test_numeric = pd.concat(
    test_numeric_parts,
    ignore_index=True
).to_numpy(dtype=np.float64)

print("Test shape:", X_test_numeric.shape)
print(
    "Memory (MB):",
    round(X_test_numeric.nbytes / (1024**2), 2)
)

Test shape: (1199393, 30)
Memory (MB): 274.52

In [129]:
rf_test_predictions = rf_full_model.predict(X_test_numeric)

rf_test_mae = mean_absolute_error(
    y_test,
    rf_test_predictions
)

rf_test_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        rf_test_predictions
    )
)

rf_test_r2 = r2_score(
    y_test,
    rf_test_predictions
)

print("FINAL RANDOM FOREST TEST RESULTS")
print("--------------------------------")
print("MAE :", rf_test_mae)
print("RMSE:", rf_test_rmse)
print("R²  :", rf_test_r2)

FINAL RANDOM FOREST TEST RESULTS
--------------------------------
MAE : 2.151949265119218
RMSE: 10.066536181453554
R²  : 0.90451028926148

In [130]:
test_error_analysis = pd.DataFrame({
    "actual": y_test,
    "predicted": rf_test_predictions
})

test_error_analysis["error"] = (
    test_error_analysis["predicted"]
    - test_error_analysis["actual"]
)

test_error_analysis["absolute_error"] = (
    test_error_analysis["error"].abs()
)

print(
    test_error_analysis
    .sort_values("absolute_error", ascending=False)
    .head(20)
    .to_string(index=False)
)

 actual   predicted        error  absolute_error
 4952.0 1903.794427 -3048.205573     3048.205573
 4641.0 1733.839287 -2907.160713     2907.160713
 2841.0    5.995128 -2835.004872     2835.004872
 4292.0 1531.379628 -2760.620372     2760.620372
 4874.0 2200.196500 -2673.803500     2673.803500
 4324.0 1852.728887 -2471.271113     2471.271113
 2300.0    6.163745 -2293.836255     2293.836255
 4298.0 2127.188020 -2170.811980     2170.811980
 3761.0 1923.675891 -1837.324109     1837.324109
 3120.0 1504.720627 -1615.279373     1615.279373
 3128.0 1714.491628 -1413.508372     1413.508372
 3480.0 2106.912054 -1373.087946     1373.087946
 3013.0 1728.220121 -1284.779879     1284.779879
 2916.0 1655.299302 -1260.700698     1260.700698
 3158.0 1899.096899 -1258.903101     1258.903101
 2699.0 1528.578219 -1170.421781     1170.421781
 3182.0 2043.996405 -1138.003595     1138.003595
 2538.0 1482.326066 -1055.673934     1055.673934
 2560.0 1515.342302 -1044.657698     1044.657698
 2824.0 1871.254239  -952.745761      952.745761

In [131]:
test_feature_query = """
SELECT
    date,
    item_id,
    store_id,
    quantity,
    price,
    promotion_flag,
    discount_pct,
    markdown_flag,
    markdown_pct,
    demand_avg_7d,
    demand_avg_28d,
    quantity_lag_1,
    quantity_lag_7,
    quantity_lag_14,
    quantity_lag_28
FROM analytics.price_sense_features
WHERE date >= '2024-07-01'
  AND date <= '2024-09-26'
ORDER BY date, item_id, store_id
"""

test_feature_data = pd.read_sql(
    test_feature_query,
    engine
)

test_feature_data["predicted"] = rf_test_predictions

test_feature_data["absolute_error"] = (
    test_feature_data["quantity"]
    - test_feature_data["predicted"]
).abs()

worst_predictions = (
    test_feature_data
    .sort_values("absolute_error", ascending=False)
    .head(20)
)

print(
    worst_predictions.to_string(index=False)
)

      date      item_id  store_id  quantity  price  promotion_flag  discount_pct  markdown_flag  markdown_pct  demand_avg_7d  demand_avg_28d  quantity_lag_1  quantity_lag_7  quantity_lag_14  quantity_lag_28  predicted  absolute_error
2024-09-14 327c5bc1e583         4    4952.0   0.01               0           NaN              0           NaN    3118.142857     3063.083333          4324.0          4641.0              NaN              NaN   3.498131     4948.501869
2024-09-21 327c5bc1e583         4    4874.0   0.01               0           NaN              0           NaN    3243.285714     3129.473684          4298.0          4952.0           4641.0              NaN   1.521981     4872.478019
2024-09-07 327c5bc1e583         4    4641.0   0.01               0           NaN              0           NaN    2986.000000     2986.000000          4292.0             NaN              NaN              NaN   9.635974     4631.364026
2024-09-20 327c5bc1e583         4    4298.0   0.01               0           NaN              0           NaN    3247.000000     3064.555556          2794.0          4324.0           4292.0              NaN   1.451026     4296.548974
2024-09-06 327c5bc1e583         4    4292.0   0.01               0           NaN              0           NaN    2659.500000     2659.500000          2699.0             NaN              NaN              NaN   4.983559     4287.016441
2024-09-13 327c5bc1e583         4    4324.0   0.01               0           NaN              0           NaN    3113.571429     2948.454545          2645.0          4292.0              NaN              NaN 255.028097     4068.971903
2024-09-25 327c5bc1e583         4    3761.0   0.01               0           NaN              0           NaN    3240.000000     3149.000000          2236.0          2621.0           2422.0              NaN  17.218940     3743.781060
2024-09-22 327c5bc1e583         4    3480.0   0.01               0           NaN              0           NaN    3232.142857     3216.700000          4874.0          3158.0           3013.0              NaN   2.987472     3477.012528
2024-09-20 327c5bc1e583         1    3182.0   0.01               0           NaN              0           NaN    2216.142857     2187.500000          2450.0          3128.0           3120.0              NaN   4.037786     3177.962214
2024-09-15 327c5bc1e583         4    3158.0   0.01               0           NaN              0           NaN    3162.571429     3208.384615          4952.0          3013.0              NaN              NaN   5.071172     3152.928828
2024-09-13 327c5bc1e583         1    3128.0   0.01               0           NaN              0           NaN    2264.857143     2169.272727          2216.0          3120.0              NaN              NaN   2.339373     3125.660627
2024-09-06 327c5bc1e583         1    3120.0   0.01               0           NaN              0           NaN    2002.000000     2002.000000          2076.0             NaN              NaN              NaN   6.860169     3113.139831
2024-09-08 327c5bc1e583         4    3013.0   0.01               0           NaN              0           NaN    3261.833333     3261.833333          4641.0             NaN              NaN              NaN   1.844879     3011.155121
2024-09-07 327c5bc1e583         1    2916.0   0.01               0           NaN              0           NaN    2225.600000     2225.600000          3120.0             NaN              NaN              NaN   5.458945     2910.541055
2024-09-02 327c5bc1e583         4    2841.0   0.01               0           NaN              0           NaN            NaN             NaN             NaN             NaN              NaN              NaN   2.034464     2838.965536
2024-09-14 327c5bc1e583         1    2824.0   0.01               0           NaN              0           NaN    2266.000000     2249.166667          3128.0          2916.0              NaN              NaN   1.771551     2822.228449
2024-09-26 327c5bc1e583         4    2797.0   0.01               0           NaN              0           NaN    3402.857143     3174.500000          3761.0          2794.0           2645.0              NaN   1.733967     2795.266033
2024-09-19 327c5bc1e583         4    2794.0   0.01               0           NaN              0           NaN    3225.714286     3080.470588          2621.0          2645.0           2699.0              NaN   2.162256     2791.837744
2024-09-05 327c5bc1e583         4    2699.0   0.01               0           NaN              0           NaN    2646.333333     2646.333333          2538.0             NaN              NaN              NaN   1.825651     2697.174349
2024-09-21 327c5bc1e583         1    2646.0   0.01               0           NaN              0           NaN    2223.857143     2239.842105          3182.0          2824.0           2916.0              NaN   3.024924     2642.975076

In [132]:
test_prices = test_feature_data["price"].to_numpy()

normal_mask = test_prices != 0.01

print("Total test rows:", len(test_prices))
print("Price = 0.01 rows:", (~normal_mask).sum())
print("Other price rows:", normal_mask.sum())

print("\n--- All test rows ---")
print("MAE :", mean_absolute_error(y_test, rf_test_predictions))
print("RMSE:", np.sqrt(mean_squared_error(y_test, rf_test_predictions)))
print("R²  :", r2_score(y_test, rf_test_predictions))

print("\n--- Excluding price = 0.01 ---")
print("MAE :", mean_absolute_error(
    y_test[normal_mask],
    rf_test_predictions[normal_mask]
))
print("RMSE:", np.sqrt(
    mean_squared_error(
        y_test[normal_mask],
        rf_test_predictions[normal_mask]
    )
))
print("R²  :", r2_score(
    y_test[normal_mask],
    rf_test_predictions[normal_mask]
))

Total test rows: 1199393
Price = 0.01 rows: 378
Other price rows: 1199015

--- All test rows ---
MAE : 2.151949265119218
RMSE: 10.066536181453554
R²  : 0.90451028926148

--- Excluding price = 0.01 ---
MAE : 2.151888865366428
RMSE: 10.067802903458274
R²  : 0.9045102010559074

In [134]:
model_comparison = pd.DataFrame([
    {
        "model": "Ridge",
        "features": "30 numeric + 2,084 one-hot",
        "training_rows": X_train_corrected.shape[0],
        "validation_mae": 2.397499,
        "validation_rmse": 7.728365,
        "validation_r2": 0.916595
    },
    {
        "model": "HistGradientBoosting",
        "features": "30 numeric",
        "training_rows": 500000,
        "validation_mae": 2.245066,
        "validation_rmse": 9.097360,
        "validation_r2": 0.884429
    },
    {
        "model": "XGBoost",
        "features": "30 numeric",
        "training_rows": 500000,
        "validation_mae": 2.220282,
        "validation_rmse": 8.943184,
        "validation_r2": 0.888313
    },
    {
        "model": "Random Forest",
        "features": "30 numeric",
        "training_rows": X_train_numeric.shape[0],
        "validation_mae": 2.217598,
        "validation_rmse": 7.132158,
        "validation_r2": 0.928967
    }
])

print(model_comparison.to_string(index=False))

print("\nFinal model: Random Forest")
print("Test MAE :", 2.151949)
print("Test RMSE:", 10.066536)
print("Test R²  :", 0.904510)

               model                   features  training_rows  validation_mae  validation_rmse  validation_r2
               Ridge 30 numeric + 2,084 one-hot        3807606        2.397499         7.728365       0.916595
HistGradientBoosting                 30 numeric         500000        2.245066         9.097360       0.884429
             XGBoost                 30 numeric         500000        2.220282         8.943184       0.888313
       Random Forest                 30 numeric        3807606        2.217598         7.132158       0.928967

Final model: Random Forest
Test MAE : 2.151949
Test RMSE: 10.066536
Test R²  : 0.90451

In [135]:
model_comparison.to_csv(
    "pricesense_model_comparison.csv",
    index=False
)

print("Model comparison saved.")
print("Rows:", len(model_comparison))

Model comparison saved.
Rows: 4

In [136]:
pricing_recommendations.to_csv(
    "pricesense_pricing_recommendations.csv",
    index=False
)

print("Pricing recommendations saved.")
print("Rows:", len(pricing_recommendations))
print("\nColumns:")
print(pricing_recommendations.columns.tolist())

Pricing recommendations saved.
Rows: 5829

Columns:
['item_id', 'store_id', 'date', 'current_demand', 'current_price', 'elasticity', 'price_change_pct', 'simulated_price', 'simulated_demand', 'simulated_revenue', 'revenue_change_pct']

In [137]:
pricing_summary = (
    pricing_recommendations
    .groupby("price_change_pct")
    .agg(
        item_store_pairs=("item_id", "count"),
        avg_current_price=("current_price", "mean"),
        avg_simulated_price=("simulated_price", "mean"),
        avg_current_demand=("current_demand", "mean"),
        avg_simulated_demand=("simulated_demand", "mean"),
        total_simulated_revenue=("simulated_revenue", "sum"),
        avg_revenue_change_pct=("revenue_change_pct", "mean")
    )
    .reset_index()
    .sort_values("price_change_pct")
)

print(pricing_summary.to_string(index=False))

 price_change_pct  item_store_pairs  avg_current_price  avg_simulated_price  avg_current_demand  avg_simulated_demand  total_simulated_revenue  avg_revenue_change_pct
            -10.0              2988         254.442795           228.998515            4.551344              5.800477             2.395680e+06                13.01248
             10.0              2841         290.375178           319.412696            2.635200              2.495811             1.400412e+06                 4.78259

In [138]:
pricing_summary.to_csv(
    "pricesense_pricing_summary.csv",
    index=False
)

print("Pricing summary saved.")
print("Rows:", len(pricing_summary))

Pricing summary saved.
Rows: 2

In [139]:
project_results = pd.DataFrame([
    {
        "section": "Demand Forecasting",
        "metric": "Validation MAE",
        "value": 2.217598
    },
    {
        "section": "Demand Forecasting",
        "metric": "Validation RMSE",
        "value": 7.132158
    },
    {
        "section": "Demand Forecasting",
        "metric": "Validation R²",
        "value": 0.928967
    },
    {
        "section": "Demand Forecasting",
        "metric": "Test MAE",
        "value": 2.151949
    },
    {
        "section": "Demand Forecasting",
        "metric": "Test RMSE",
        "value": 10.066536
    },
    {
        "section": "Demand Forecasting",
        "metric": "Test R²",
        "value": 0.904510
    },
    {
        "section": "Pricing",
        "metric": "Item-store pairs evaluated",
        "value": 5829
    },
    {
        "section": "Pricing",
        "metric": "Pairs recommended -10%",
        "value": 2988
    },
    {
        "section": "Pricing",
        "metric": "Pairs recommended +10%",
        "value": 2841
    }
])

print(project_results.to_string(index=False))

           section                     metric       value
Demand Forecasting             Validation MAE    2.217598
Demand Forecasting            Validation RMSE    7.132158
Demand Forecasting              Validation R²    0.928967
Demand Forecasting                   Test MAE    2.151949
Demand Forecasting                  Test RMSE   10.066536
Demand Forecasting                    Test R²    0.904510
           Pricing Item-store pairs evaluated 5829.000000
           Pricing     Pairs recommended -10% 2988.000000
           Pricing     Pairs recommended +10% 2841.000000

In [140]:
project_results.to_csv(
    "pricesense_project_results.csv",
    index=False
)

print("Project results saved.")
print("Rows:", len(project_results))

Project results saved.
Rows: 9

## Final Model Selection

Four regression approaches were evaluated using the validation dataset:

- Ridge Regression
- HistGradientBoosting
- XGBoost
- Random Forest

Random Forest was selected as the final demand forecasting model because it achieved the strongest validation performance across all three evaluation metrics:

- **MAE:** 2.2176
- **RMSE:** 7.1322
- **R²:** 0.9290

The final Random Forest was trained on the full training period (2022-08-28 to 2023-12-31) using 30 numeric features.

The untouched test period (2024-07-01 to 2024-09-26) produced:

- **MAE:** 2.1519
- **RMSE:** 10.0665
- **R²:** 0.9045

The increase in RMSE on the test period is mainly influenced by rare extreme-demand observations. These observations were investigated rather than removed solely to improve model performance.

Therefore, Random Forest is retained as the final demand forecasting model for PriceSense.

In [3]:
import pandas as pd

pricing_recommendations = pd.read_csv(
    "pricesense_pricing_recommendations.csv"
)

print("Rows:", len(pricing_recommendations))
print("Columns:", pricing_recommendations.columns.tolist())
print("\nFirst 5 rows:")
display(pricing_recommendations.head())

Rows: 5829
Columns: ['item_id', 'store_id', 'date', 'current_demand', 'current_price', 'elasticity', 'price_change_pct', 'simulated_price', 'simulated_demand', 'simulated_revenue', 'revenue_change_pct']

First 5 rows:

,item_id,store_id,date,current_demand,current_price,elasticity,price_change_pct,simulated_price,simulated_demand,simulated_revenue,revenue_change_pct
0,001829cb707d,1,2024-09-26,1.0,149.90,-0.191222,10.0,164.890,0.981940,161.912039,8.013368
1,001829cb707d,2,2024-09-25,2.0,142.41,-1.221127,-10.0,128.169,2.274604,291.533662,2.357160
2,00274a69c705,4,2024-09-26,2.0,35.90,-1.322994,-10.0,32.310,2.299148,74.285461,3.461645
3,002f51c34a7a,1,2024-09-26,6.0,97.90,-1.273648,-10.0,88.110,6.861676,604.582262,2.925138
4,004c615c8f87,1,2024-09-20,1.0,369.00,-1.855222,-10.0,332.100,1.215879,403.793349,9.429092

In [4]:
from sqlalchemy import create_engine

DB_USER = "postgres"
DB_PASSWORD = "2004"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "pricesense"

engine = create_engine(
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

print("PostgreSQL engine created successfully.")

PostgreSQL engine created successfully.

In [5]:
pricing_recommendations.to_sql(
    "pricing_recommendations",
    engine,
    schema="analytics",
    if_exists="append",
    index=False
)

print("Pricing recommendations loaded into PostgreSQL.")

Pricing recommendations loaded into PostgreSQL.

In [6]:
check = pd.read_sql(
    """
    SELECT
        COUNT(*) AS total_rows,
        COUNT(DISTINCT item_id || '-' || store_id) AS unique_item_store_pairs,
        MIN(date) AS earliest_date,
        MAX(date) AS latest_date
    FROM analytics.pricing_recommendations;
    """,
    engine
)

display(check)

   total_rows  unique_item_store_pairs earliest_date latest_date
0        5829                     5829    2024-07-01  2024-09-26

In [7]:
check = pd.read_sql(
    """
    SELECT
        COUNT(*) AS total_rows,
        COUNT(DISTINCT item_id) AS unique_items,
        COUNT(DISTINCT store_id) AS unique_stores,
        MIN(date) AS earliest_date,
        MAX(date) AS latest_date
    FROM analytics.pricing_recommendations;
    """,
    engine
)

print(check.to_string(index=False))

 total_rows  unique_items  unique_stores earliest_date latest_date
       5829          4298              4    2024-07-01  2024-09-26

In [8]:
pricing_summary = pd.read_csv(
    "pricesense_pricing_summary.csv"
)

print("Rows:", len(pricing_summary))
print("\nColumns:")
print(pricing_summary.columns.tolist())

display(pricing_summary)

Rows: 2

Columns:
['price_change_pct', 'item_store_pairs', 'avg_current_price', 'avg_simulated_price', 'avg_current_demand', 'avg_simulated_demand', 'total_simulated_revenue', 'avg_revenue_change_pct']

,price_change_pct,item_store_pairs,avg_current_price,avg_simulated_price,avg_current_demand,avg_simulated_demand,total_simulated_revenue,avg_revenue_change_pct
0,-10.0,2988,254.442795,228.998515,4.551344,5.800477,2.395680e+06,13.01248
1,10.0,2841,290.375178,319.412696,2.635200,2.495811,1.400412e+06,4.78259

In [9]:
pricing_summary.to_sql(
    "pricing_summary",
    engine,
    schema="analytics",
    if_exists="append",
    index=False
)

print("Pricing summary loaded into PostgreSQL.")

Pricing summary loaded into PostgreSQL.

In [10]:
verification = pd.read_sql(
    """
    SELECT
        'pricing_recommendations' AS table_name,
        COUNT(*) AS row_count
    FROM analytics.pricing_recommendations

    UNION ALL

    SELECT
        'pricing_summary' AS table_name,
        COUNT(*) AS row_count
    FROM analytics.pricing_summary;
    """,
    engine
)

display(verification)

                table_name  row_count
0  pricing_recommendations       5829
1          pricing_summary          2

In [11]:
model_check = pd.read_sql(
    """
    SELECT
        model,
        training_rows,
        validation_mae,
        validation_rmse,
        validation_r2
    FROM analytics.model_comparison
    ORDER BY validation_r2 DESC;
    """,
    engine
)

display(model_check)

,model,training_rows,validation_mae,validation_rmse,validation_r2
0,Random Forest,3807606,2.217598,7.132158,0.928967
1,Ridge,3807606,2.397499,7.728365,0.916595
2,XGBoost,500000,2.220282,8.943184,0.888313
3,HistGradientBoosting,500000,2.245066,9.097360,0.884429

In [13]:
import os

project_root = r"C:\Users\ADMIN\Desktop\PriceSense"

for root, dirs, files in os.walk(project_root):
    for file in files:
        if any(keyword in file.lower() for keyword in ["predict", "forecast", "test_pred"]):
            print(os.path.join(root, file))

In [4]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

DB_USER = "postgres"
DB_PASSWORD = "2004"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "pricesense"

engine = create_engine(
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

print("Connection established:", engine)

Connection established: Engine(postgresql+psycopg2://postgres:***@localhost:5432/pricesense)

In [ ]:
model_query = """
SELECT
    date,
    item_id,
    store_id,
    quantity,
    price,
    year,
    month,
    week,
    day_of_week,
    is_weekend,
    weight_volume,
    weight_netto,
    fatness,
    area,
    store_demand_avg_28d,
    previous_price,
    promotion_flag,
    promo_type_code,
    time_promo,
    discount_pct,
    quantity_lag_1,
    quantity_lag_7,
    quantity_lag_14,
    quantity_lag_28,
    demand_avg_7d,
    demand_avg_28d,
    demand_volatility_28d,
    demand_trend_7d,
    price_vs_previous_pct,
    demand_momentum_7d,
    promo_discount_interaction,
    promo_price_change_interaction,
    markdown_flag,
    markdown_pct
FROM analytics.price_sense_features
ORDER BY date, item_id, store_id
"""

df_model = pd.read_sql(model_query, engine)

print("Shape:", df_model.shape)
print("Date range:", df_model["date"].min(), "to", df_model["date"].max())
print("Columns:", len(df_model.columns))

In [1]:
categorical_features = [
    "dept_name",
    "class_name",
    "subclass_name",
    "item_type",
    "division",
    "format",
    "city"
]

numeric_features_corrected = [
    "price",
    "year",
    "month",
    "week",
    "day_of_week",
    "is_weekend",
    "weight_volume",
    "weight_netto",
    "fatness",
    "area",
    "store_demand_avg_28d",
    "previous_price",
    "promotion_flag",
    "promo_type_code",
    "time_promo",
    "discount_pct",
    "quantity_lag_1",
    "quantity_lag_7",
    "quantity_lag_14",
    "quantity_lag_28",
    "demand_avg_7d",
    "demand_avg_28d",
    "demand_volatility_28d",
    "demand_trend_7d",
    "price_vs_previous_pct",
    "demand_momentum_7d",
    "promo_discount_interaction",
    "promo_price_change_interaction",
    "markdown_flag",
    "markdown_pct"
]

print("Categorical features:", len(categorical_features))
print("Numeric features:", len(numeric_features_corrected))

Categorical features: 7
Numeric features: 30

In [5]:
import pandas as pd

train_query = """
SELECT
    quantity,
    price,
    year,
    month,
    week,
    day_of_week,
    is_weekend,
    weight_volume,
    weight_netto,
    fatness,
    area,
    store_demand_avg_28d,
    previous_price,
    promotion_flag,
    promo_type_code,
    time_promo,
    discount_pct,
    quantity_lag_1,
    quantity_lag_7,
    quantity_lag_14,
    quantity_lag_28,
    demand_avg_7d,
    demand_avg_28d,
    demand_volatility_28d,
    demand_trend_7d,
    price_vs_previous_pct,
    demand_momentum_7d,
    promo_discount_interaction,
    promo_price_change_interaction,
    markdown_flag,
    markdown_pct
FROM analytics.price_sense_features
WHERE date >= '2022-08-28'
  AND date <= '2023-12-31'
"""

df_train = pd.read_sql(train_query, engine)

print("Training shape:", df_train.shape)
print("Target rows:", len(df_train))
print("Missing values:", df_train.isna().sum().sum())

Training shape: (3807606, 31)
Target rows: 3807606
Missing values: 19743736

In [6]:
# Separate target and features
X_train_raw = df_train[numeric_features_corrected].copy()
y_train_corrected = df_train["quantity"].copy()

# Preserve the original missing-value treatment
X_train_raw["discount_pct"] = X_train_raw["discount_pct"].fillna(0)
X_train_raw["markdown_pct"] = X_train_raw["markdown_pct"].fillna(0)

# Training-only medians
train_medians = X_train_raw.median()

# Fill remaining numeric missing values using training medians
X_train_corrected_df = X_train_raw.fillna(train_medians)

print("X shape:", X_train_corrected_df.shape)
print("y shape:", y_train_corrected.shape)
print("Remaining missing values:", X_train_corrected_df.isna().sum().sum())

X shape: (3807606, 30)
y shape: (3807606,)
Remaining missing values: 0

In [7]:
from sklearn.ensemble import RandomForestRegressor

rf_full_model = RandomForestRegressor(
    n_estimators=50,
    max_depth=12,
    min_samples_leaf=5,
    max_features="sqrt",
    random_state=42,
    n_jobs=-1
)

rf_full_model.fit(X_train_corrected_df, y_train_corrected)

print("Random Forest training completed.")

Random Forest training completed.

In [8]:
test_query = """
SELECT
    date,
    item_id,
    store_id,
    quantity,
    price,
    year,
    month,
    week,
    day_of_week,
    is_weekend,
    weight_volume,
    weight_netto,
    fatness,
    area,
    store_demand_avg_28d,
    previous_price,
    promotion_flag,
    promo_type_code,
    time_promo,
    discount_pct,
    quantity_lag_1,
    quantity_lag_7,
    quantity_lag_14,
    quantity_lag_28,
    demand_avg_7d,
    demand_avg_28d,
    demand_volatility_28d,
    demand_trend_7d,
    price_vs_previous_pct,
    demand_momentum_7d,
    promo_discount_interaction,
    promo_price_change_interaction,
    markdown_flag,
    markdown_pct
FROM analytics.price_sense_features
WHERE date >= '2024-07-01'
  AND date <= '2024-09-26'
ORDER BY date, item_id, store_id
"""

df_test = pd.read_sql(test_query, engine)

print("Test shape:", df_test.shape)
print("Date range:", df_test["date"].min(), "to", df_test["date"].max())
print("Missing values:", df_test[numeric_features_corrected].isna().sum().sum())

Test shape: (1199393, 34)
Date range: 2024-07-01 to 2024-09-26
Missing values: 5797271

In [9]:
X_test_raw = df_test[numeric_features_corrected].copy()
y_test_corrected = df_test["quantity"].copy()

# Same special handling used for training
X_test_raw["discount_pct"] = X_test_raw["discount_pct"].fillna(0)
X_test_raw["markdown_pct"] = X_test_raw["markdown_pct"].fillna(0)

# IMPORTANT:
# Use medians calculated from TRAINING data only
X_test_corrected_df = X_test_raw.fillna(train_medians)

print("X test shape:", X_test_corrected_df.shape)
print("y test shape:", y_test_corrected.shape)
print("Remaining missing values:", X_test_corrected_df.isna().sum().sum())

X test shape: (1199393, 30)
y test shape: (1199393,)
Remaining missing values: 0

In [10]:
test_predictions = rf_full_model.predict(X_test_corrected_df)

print("Predictions generated:", len(test_predictions))
print("Min prediction:", test_predictions.min())
print("Max prediction:", test_predictions.max())
print("Mean prediction:", test_predictions.mean())

Predictions generated: 1199393
Min prediction: -22.137255788034985
Max prediction: 2308.980633624545
Mean prediction: 5.8536187187641415

In [11]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

test_mae = mean_absolute_error(y_test_corrected, test_predictions)
test_rmse = np.sqrt(mean_squared_error(y_test_corrected, test_predictions))
test_r2 = r2_score(y_test_corrected, test_predictions)

print(f"Test MAE : {test_mae:.6f}")
print(f"Test RMSE: {test_rmse:.6f}")
print(f"Test R²  : {test_r2:.6f}")

Test MAE : 2.145074
Test RMSE: 9.701083
Test R²  : 0.911318

In [12]:
negative_predictions = (test_predictions < 0).sum()
zero_or_negative_actuals = (y_test_corrected <= 0).sum()

print("Negative predictions:", negative_predictions)
print("Percentage negative predictions:",
      round(negative_predictions / len(test_predictions) * 100, 4), "%")

print("Zero/negative actual demand:", zero_or_negative_actuals)

Negative predictions: 2
Percentage negative predictions: 0.0002 %
Zero/negative actual demand: 372

In [13]:
forecast_output = df_test[
    ["date", "item_id", "store_id", "quantity"]
].copy()

forecast_output["predicted_demand"] = test_predictions

forecast_output = forecast_output.rename(
    columns={"quantity": "actual_demand"}
)

print("Forecast rows:", len(forecast_output))
print("Columns:", forecast_output.columns.tolist())
print("Unique sales grain:",
      forecast_output[["date", "item_id", "store_id"]].drop_duplicates().shape[0])

Forecast rows: 1199393
Columns: ['date', 'item_id', 'store_id', 'actual_demand', 'predicted_demand']
Unique sales grain: 1199393

In [14]:
forecast_path = r"C:\Users\ADMIN\Desktop\PriceSense\notebooks\pricesense_forecast.csv"

forecast_output.to_csv(
    forecast_path,
    index=False
)

print("Saved:", forecast_path)
print("File rows:", len(forecast_output))

Saved: C:\Users\ADMIN\Desktop\PriceSense\notebooks\pricesense_forecast.csv
File rows: 1199393

# PriceSense — Demand Forecasting & Dynamic Pricing Decision Engine

PriceSense is an end-to-end retail analytics project that combines SQL-based data preparation, demand forecasting, price-elasticity analysis, pricing simulation, and Power BI reporting. The goal is to turn historical retail data into a structured workflow for understanding demand and evaluating data-driven pricing decisions.

The project follows the analytics process from raw source data through preparation and feature engineering to model outputs, pricing scenarios, and an interactive business dashboard. PostgreSQL is used for the database and analytical transformations, Python/Jupyter notebooks are used for model-related work, and Power BI is used to present the results.

> **Important interpretation note:** PriceSense produces model-based forecasts and simulated pricing outcomes. Simulated revenue uplift is an estimate under the model assumptions, not proof of realized business impact. The current pricing recommendation outputs cover **1 July 2024 to 26 September 2024**; they should not be interpreted as recommendations for the entire historical dataset.

---

## Contents

- [Project at a glance](#project-at-a-glance)
- [Business problem](#business-problem)
- [Project objectives](#project-objectives)
- [Dataset](#dataset)
- [Technology stack](#technology-stack)
- [End-to-end workflow](#end-to-end-workflow)
- [Database architecture](#database-architecture)
- [Feature engineering](#feature-engineering)
- [Demand forecasting](#demand-forecasting)
- [Price elasticity and pricing simulation](#price-elasticity-and-pricing-simulation)
- [Pricing recommendations](#pricing-recommendations)
- [Model results](#model-results)
- [Power BI dashboard](#power-bi-dashboard)
- [Repository structure](#repository-structure)
- [How to reproduce the project](#how-to-reproduce-the-project)
- [Data and repository considerations](#data-and-repository-considerations)
- [Limitations and responsible interpretation](#limitations-and-responsible-interpretation)
- [Future improvements](#future-improvements)
- [Author](#author)

---

## Project at a glance

| Item | Description |
|---|---|
| Project | PriceSense — Demand Forecasting & Dynamic Pricing Decision Engine |
| Domain | Retail analytics, demand forecasting, pricing analytics |
| Database | PostgreSQL |
| Analysis and modelling | Python, Pandas, Jupyter Notebook, scikit-learn |
| Business intelligence | Power BI, DAX |
| Main analytical grain | Date + item + store, where supported by the source data |
| Historical price data | 28 August 2022 – 26 September 2024 |
| Stores | 4 |
| Main forecasting model | Random Forest |
| Main outputs | Forecasts, model comparison/performance, price-elasticity analysis, pricing recommendations, pricing scenarios, Power BI dashboard |

## Business problem

Retail businesses need to understand how much demand they may receive and how pricing decisions could affect sales and revenue. Historical sales alone are not enough: demand may also vary with product, store, date, promotions, markdowns, and other factors. Pricing decisions therefore need to be evaluated in context rather than treated as isolated percentage changes.

PriceSense brings these tasks into one analytical workflow. It prepares retail data for analysis, engineers demand-related features, evaluates forecasting performance, uses price elasticity to simulate alternative prices, and presents the resulting information in a Power BI dashboard.

The project is a portfolio and decision-support exercise. It demonstrates an analytical approach; it does not claim that simulated pricing outcomes have been deployed or verified in a live retail environment.

## Project objectives

1. **Prepare and validate retail data** using a layered PostgreSQL workflow.
2. **Understand the data** through profiling, quality checks, and analytical queries.
3. **Build demand-related features** using sales history, calendar information, product and store attributes, prices, promotions, and markdowns where available.
4. **Forecast demand** and compare model performance using appropriate evaluation metrics.
5. **Analyse price elasticity** to estimate how demand could respond to a change in price.
6. **Simulate pricing alternatives** and compare their estimated demand and revenue.
7. **Generate pricing recommendations** from the modelled scenarios.
8. **Communicate results** through a multi-page Power BI dashboard.

---

## Dataset

The project uses the **Svizor Retail Sales Forecasting Data** dataset downloaded from Kaggle. The source files cover four stores and approximately 25 months of retail history.

The original files used in the project are:

- `sales.csv`
- `catalog.csv`
- `stores.csv`
- `price_history.csv`
- `discounts_history.csv`
- `markdowns.csv`
- `online.csv`
- `actual_matrix.csv`

The source data includes retail sales and quantity information, item/catalog attributes, store information, price history, discounts, markdowns, and online-related data. The files differ in size and grain, so they need to be joined and aggregated carefully rather than treated as if every row represented the same type of observation.

The main analytical grain used for demand modelling is **date + item ID + store ID**, where the source tables support that level of detail.

### Data scale and profiling

The `sales.csv` source contains approximately **7.43 million rows**. The wider source files range from small reference tables to multi-million-row history tables. Profiling also identified substantial missingness in some product attributes and promotion/discount fields. Missing values therefore need to be interpreted according to the meaning of each field rather than automatically replaced with zero.

The recorded price-history date range is **28 August 2022 to 26 September 2024**. Preserve this source coverage when reproducing the analysis; do not assume that every derived table or model output spans the entire period.

### Obtaining the data

The raw CSV files are not included in this repository because of their size and to avoid unnecessary duplication of the original dataset. Obtain the dataset from its original Kaggle source and place the files in a local data directory before running the relevant import and preparation steps.

---

## Technology stack

- **PostgreSQL** — relational database, schema organization, SQL transformations, profiling, analytical features, validation, and reporting tables.
- **SQL** — table creation, data preparation, joins, aggregations, feature construction, quality checks, and output validation.
- **Python** — modelling workflow and supporting data analysis.
- **Pandas** — data handling and analysis in notebooks.
- **Jupyter Notebook** — exploratory work, model comparison, and model-related analysis.
- **scikit-learn** — demand forecasting with a Random Forest model and evaluation using standard regression metrics.
- **Power BI** — interactive reporting and decision-support dashboard.
- **DAX** — measures, KPIs, period comparisons, and dashboard calculations.
- **Git and GitHub** — version control and project documentation.

---

## End-to-end workflow

```text
Kaggle retail data
        ↓
Raw CSV files
        ↓
PostgreSQL: raw schema
        ↓
Profiling and data-quality checks
        ↓
PostgreSQL: staging schema
        ↓
Cleaning, standardisation, and validation
        ↓
PostgreSQL: analytics schema
        ↓
Demand, calendar, product, store, price,
promotion, markdown, and rolling features
        ↓
Python / Jupyter model development
        ↓
Demand forecasts and model evaluation
        ↓
Price elasticity analysis
        ↓
Pricing scenario simulation
        ↓
Pricing recommendations and summary outputs
        ↓
Power BI semantic model, DAX measures, and dashboard
        ↓
Business interpretation and limitations
```

The database is layered to separate source data from prepared data and analytical outputs. The exact execution order of individual scripts should be confirmed against their dependencies before rerunning the workflow on a fresh database.

---

## Database architecture

The PostgreSQL database is named `pricesense`. The main schemas are `raw`, `staging`, and `analytics`; a default `public` schema is also present in PostgreSQL.

### 1. `raw` schema

The `raw` schema holds the imported source tables:

- `actual_matrix`
- `catalog`
- `discounts_history`
- `markdowns`
- `online`
- `price_history`
- `sales`
- `stores`

This layer preserves the source-oriented representation of the imported files. It is useful for tracing downstream calculations back to the original data.

### 2. `staging` schema

The `staging` schema contains corresponding tables for the eight source datasets. This layer is intended for prepared and validated data used in subsequent transformations.

The existence of tables with matching names in `raw` and `staging` does not, by itself, prove that their contents or structures differ in every respect. The SQL transformations and validation checks determine what was changed between layers.

### 3. `analytics` schema

The `analytics` schema contains source-like/reference tables, enriched tables, engineered features, model outputs, and pricing outputs. The current database inventory includes the following 28 tables.

**Source and reference data**
- `actual_matrix`
- `catalog`
- `discounts_history`
- `markdowns`
- `online`
- `price_history`
- `sales`
- `stores`
- `product_class_translation`
- `store_history`

**Demand and feature engineering**
- `daily_store_demand`
- `sales_calendar_features`
- `sales_demand_features`
- `sales_derived_features`
- `sales_markdown_features`
- `sales_price_features`
- `sales_product_features`
- `sales_promotion_features`
- `sales_rolling_features`
- `sales_store_features`
- `price_history_enriched`
- `price_sense_features`

**Model and pricing outputs**
- `model_comparison`
- `model_forecast`
- `model_performance`
- `pricing_recommendations`
- `pricing_scenarios`
- `pricing_summary`

This inventory reflects the database as inspected during project development. Table names alone do not define the full dependency order; consult the SQL scripts and notebook workflow before rebuilding the database.

---

## Feature engineering

Demand forecasting depends on more than a single sales quantity column. PriceSense constructs analytical tables to bring demand history together with relevant time, product, store, price, promotion, and markdown information.

The known feature-engineering areas include:

- **Demand features:** historical demand and related derived values.
- **Calendar features:** date-related attributes for time-aware analysis.
- **Rolling features:** rolling demand summaries that capture recent history.
- **Lag features:** prior demand values, including lag periods such as 1, 7, 14, and 28 days where applicable.
- **Price features:** price-history enrichment and price-related fields.
- **Promotion and markdown features:** fields describing promotional or markdown context where available.
- **Product features:** catalog and product-level attributes.
- **Store features:** store-level information.
- **Derived features:** combined or transformed variables prepared for modelling.

The project uses the date-item-store grain for core demand analysis where supported by the data. When building lag and rolling features, rows must be correctly ordered within the relevant item/store series; feature generation must not accidentally use future observations to predict the past. Missing values near the beginning of a series are expected for some lag windows and should be handled deliberately.

---

## Demand forecasting

The demand-forecasting component uses a **Random Forest regression model** to estimate demand from engineered historical features.

The modelling workflow includes:

1. Preparing the modelling dataset from the engineered features.
2. Splitting observations into training, validation, and test sets according to the notebook workflow.
3. Fitting and comparing model candidates.
4. Evaluating forecasts with regression metrics.
5. Saving or exposing forecast and model-performance results for downstream analysis.

### Evaluation metrics

- **MAE (Mean Absolute Error):** the average absolute difference between predicted and actual demand. Lower is better.
- **RMSE (Root Mean Squared Error):** penalises larger errors more heavily than MAE. Lower is better.
- **R² (Coefficient of Determination):** indicates how much of the variation in the target is explained by the model relative to a baseline. Higher is generally better, but it should be interpreted alongside error metrics and the evaluation setup.

The recorded metrics for the current Random Forest workflow are documented in the [Model results](#model-results) section. These scores describe performance on the evaluated data splits; they do not guarantee the same performance in a future deployment.

---

## Price elasticity and pricing simulation

PriceSense includes a price-elasticity component to estimate how demand may respond to a simulated price change.

In the simulation, demand is adjusted using the current demand estimate, the ratio between simulated and current price, and the estimated elasticity:

$$
Q_{\mathrm{sim}} = Q_{\mathrm{current}}
\left(\frac{P_{\mathrm{sim}}}{P_{\mathrm{current}}}\right)^{\varepsilon}
$$

Where:

- $Q_{\mathrm{sim}}$ is simulated demand.
- $Q_{\mathrm{current}}$ is the demand estimate used as the baseline.
- $P_{\mathrm{sim}}$ is the proposed simulated price.
- $P_{\mathrm{current}}$ is the current price.
- $\varepsilon$ is the price-elasticity estimate.

Simulated revenue is then calculated as:

$$
R_{\mathrm{sim}} = P_{\mathrm{sim}} \times Q_{\mathrm{sim}}
$$

This approach enables comparison of candidate prices under the elasticity assumptions. The output is a scenario estimate, not a causal experiment. Its usefulness depends on the quality and stability of the elasticity estimates, the suitability of the baseline demand, and the validity of the assumptions for the product/store/time being evaluated.

---

## Pricing recommendations

The pricing component evaluates alternative prices and produces recommendation and summary outputs. The current database includes:

- `pricing_recommendations` — recommendation-level outputs.
- `pricing_scenarios` — alternative simulated price scenarios.
- `pricing_summary` — summary outputs used for analysis and reporting.

The recorded recommendation output includes price increases and price decreases of **10%**. The current recommendation table contains recommendations for the period **1 July 2024 to 26 September 2024**. The recorded counts are:

| Recommendation action | Rows |
|---|---:|
| Price decrease (-10%) | 2,988 |
| Price increase (+10%) | 2,841 |

These are counts in the recorded output table, not counts of unique products unless the table grain establishes that equivalence. The recorded `pricing_recommendations` output did not include a “No Change” recommendation category.

The scenario table has approximately **29,145 rows**, with five scenarios per recommendation combination in the recorded workflow. Verify the exact keys and scenario definitions in SQL before interpreting these as independent recommendations.

---

## Model results

The recorded Random Forest evaluation metrics are:

| Evaluation split | MAE | RMSE | R² |
|---|---:|---:|---:|
| Test | 2.145074 | 9.701083 | 0.911318 |
| Validation | 2.217598 | 7.132158 | 0.928967 |

These values are included to document the current recorded run. For a formal model comparison, the train/validation/test split strategy, target definition, feature set, and metric calculation should be kept consistent across models. The metrics should not be compared directly with scores from a different split or target definition without accounting for those differences.

The database also contains `model_comparison`, `model_forecast`, and `model_performance` outputs to support inspection of candidate models, forecast values, and evaluation results.

---

## Power BI dashboard

The Power BI report presents the analysis through four pages. It is designed to let a viewer move from an overall business summary to demand behaviour, pricing analysis, and model/recommendation detail.

### 1. Executive Overview

Provides a high-level view of business and pricing indicators. The planned six KPI cards are:

- Total Revenue
- Net Units Sold
- Active Products
- Average Selling Price
- Recommended Price Change %
- Recommended Revenue Change %

The page also includes trend indicators and supporting visuals. Historical sales KPIs and model-generated recommendation KPIs have different coverage: recommendation measures should be interpreted within the available July–September 2024 recommendation period.

### 2. Demand Analysis

Explores demand patterns using sales history and engineered demand features. It is intended to help users examine how demand varies over time and across the available product/store dimensions.

### 3. Pricing & Elasticity

Focuses on price history, price changes, and estimated price elasticity. It helps communicate how simulated demand and revenue can change under alternative price assumptions.

### 4. Pricing Recommendations & Model Performance

Brings together the model results and pricing outputs, including recommendation actions, simulated scenarios, and forecast/model-performance information.

### Dashboard design

The dashboard uses a pale blue-white background with navy and teal accents, white visual cards, and restrained gridlines. The design prioritises readability and business interpretation over decorative visuals. KPI trend colours and indicators are used to distinguish positive, negative, and neutral/undefined changes.

---

## Repository structure

The repository is intended to keep the project understandable without committing large raw datasets or database exports.

```text
PriceSense/
├── README.md
├── .gitignore
├── sql/
│   ├── 01_raw/
│   ├── 02_staging/
│   ├── 03_analytics/
│   ├── 04_model_pricing/
│   ├── 05_powerbi_views/
│   ├── 06_reference_translation/
│   └── 07_validation/
├── notebooks/
│   └── Jupyter notebooks used for profiling and modelling
├── powerbi dashboard/
│   └── PriceSense Power BI report (.pbix)
└── report/
    └── Project report and supporting documentation
```

The SQL directories group scripts by purpose. The exact scripts should be reviewed for completeness, dependency order, and safe re-execution before treating the repository as a one-click rebuild. Notebook and report folders may contain only the artifacts that are actually available and ready to publish.

---

## How to reproduce the project

The workflow below describes the intended process. The exact SQL execution sequence and Python paths must be confirmed from the checked-in scripts and notebooks before running them on a new machine.

1. **Obtain the source dataset.** Download the original CSV files from the dataset's Kaggle source and review its terms of use.
2. **Set up PostgreSQL.** Create a database named `pricesense` and the required schemas (`raw`, `staging`, and `analytics`) if they do not already exist.
3. **Configure local file paths.** Update any `COPY`, import, or notebook paths to match the local machine. Do not commit machine-specific paths or credentials.
4. **Load raw tables.** Import the source CSV files into the `raw` schema using the appropriate column definitions and data types.
5. **Prepare staging tables.** Run the staging transformations and validate row counts, nulls, duplicates, date ranges, and key fields.
6. **Build analytical features.** Execute the required analytics transformations in dependency order and validate their output grain and row counts.
7. **Run the modelling workflow.** Open the relevant notebooks, configure input/output paths, run the model comparison and forecasting workflow, and confirm the recorded metrics.
8. **Build pricing outputs.** Run the pricing and scenario workflow only after its required feature, forecast, and elasticity inputs are available.
9. **Connect Power BI.** Configure the database connection, verify relationships and date handling, and refresh the report. Confirm that visuals reflect the expected date coverage.
10. **Validate the final results.** Compare dashboard figures with the database outputs and note the date range, assumptions, and limitations when interpreting recommendations.

**Do not run every SQL file blindly in an existing database.** Some scripts may create or replace tables/views, depend on earlier outputs, or use local file paths. Review the script and its dependencies before execution.

---

## Data and repository considerations

To keep the repository useful and manageable:

- Do not commit the original multi-million-row CSV files unless there is a clear, permitted reason to distribute them.
- Do not commit large generated forecast exports or full database dumps by default.
- Include SQL scripts, documentation, notebooks, and dashboard/report artifacts that are appropriate to share.
- Where helpful, include small, non-sensitive sample outputs or aggregate summaries instead of full exports.
- Keep credentials, passwords, local connection strings, and machine-specific paths out of version control.
- Use `.gitignore` for local datasets, temporary files, caches, and large generated outputs.
- Add clear instructions for obtaining the source data and configuring paths locally.

The database itself is not stored in GitHub as live PostgreSQL tables. The repository stores the scripts and documentation needed to explain and, after validation, reproduce the workflow.

---

## Limitations and responsible interpretation

- **Forecasts are estimates.** Model metrics describe performance on the evaluated splits and may not generalise to future periods or changing retail conditions.
- **Pricing scenarios are simulated.** Simulated revenue uplift is not observed revenue uplift and should not be presented as a realised business result.
- **Elasticity assumptions matter.** Demand responses may vary by product, store, time, promotion, availability, and market conditions.
- **Recommendation coverage is limited.** The recorded pricing recommendations cover 1 July 2024 through 26 September 2024, not the entire historical dataset.
- **Source data contains missing values.** Missing product attributes and promotion/discount fields can affect analysis; handling decisions should be documented.
- **Data grain must be respected.** Joining tables with different grains without checking keys can duplicate records and distort sales, demand, or revenue calculations.
- **Historical associations are not automatically causal.** A relationship between price and demand in observational data does not, by itself, prove that a price change caused a demand change.
- **Reproducibility requires environment details.** Dataset access, PostgreSQL setup, Python package versions, file paths, and execution order should be documented and tested.

---

## Future improvements

Potential next steps include:

- Verify and document a clean, dependency-aware SQL execution order for a fresh database.
- Add a requirements file or environment specification for the Python workflow.
- Add reproducible backtesting and compare forecasting approaches using a consistent evaluation design.
- Validate elasticity estimates and test recommendation sensitivity to different assumptions.
- Add historical pricing backtesting before making stronger claims about business impact.
- Improve automated data-quality checks and document expected row counts and grains.
- Add small, shareable sample outputs or screenshots to make the repository easier to review.
- Document dashboard measures, filters, and relationships so the report can be maintained more easily.

These are potential improvements, not claims that they have already been completed.

---

## Author

**Nitin B. Mirajkar**

PriceSense was developed as a personal portfolio project to practise and demonstrate SQL-based analytics, demand forecasting, price-elasticity analysis, pricing simulation, and Power BI reporting.